# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: autonomic/ext/telemetry/distribution.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'autonomic/ext/telemetry/distribution.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*autonomic/ext/telemetry/distribution.proto\x12\x17\x61utonomic.ext.telemetry\"\xef\x05\n\x0c\x44istribution\x12\r\n\x05\x63ount\x18\x01 \x01(\x03\x12\x0c\n\x04mean\x18\x02 \x01(\x01\x12 \n\x18sum_of_squared_deviation\x18\x03 \x01(\x01\x12:\n\x05range\x18\x04 \x01(\x0b\x32+.autonomic.ext.telemetry.Distribution.Range\x12K\n\x0e\x62ucket_options\x18\x06 \x01(\x0b\x32\x33.autonomic.ext.telemetry.Distribution.BucketOptions\x12\x15\n\rbucket_counts\x18\x07 \x03(\x03\x1a!\n\x05Range\x12\x0b\n\x03min\x18\x01 \x01(\x01\x12\x0b\n\x03max\x18\x02 \x01(\x01\x1a\xdc\x03\n\rBucketOptions\x12T\n\x0elinear_buckets\x18\x01 \x01(\x0b\x32:.autonomic.ext.telemetry.Distribution.BucketOptions.LinearH\x00\x12^\n\x13\x65xponential_buckets\x18\x02 \x01(\x0b\x32?.autonomic.ext.telemetry.Distribution.BucketOptions.ExponentialH\x00\x12X\n\x10\x65xplicit_buckets\x18\x03 \x01(\x0b\x32<.autonomic.ext.telemetry.Distribution.BucketOptions.ExplicitH\x00\x1a\x43\n\x06Linear\x12\x1a\n\x12num_finite_buckets\x18\x01 \x01(\x05\x12\r\n\x05width\x18\x02 \x01(\x01\x12\x0e\n\x06offset\x18\x03 \x01(\x01\x1aO\n\x0b\x45xponential\x12\x1a\n\x12num_finite_buckets\x18\x01 \x01(\x05\x12\x15\n\rgrowth_factor\x18\x02 \x01(\x01\x12\r\n\x05scale\x18\x03 \x01(\x01\x1a\x1a\n\x08\x45xplicit\x12\x0e\n\x06\x62ounds\x18\x01 \x03(\x01\x42\t\n\x07optionsB\x8b\x01\n\x1b\x63om.autonomic.ext.telemetryB\x11\x44istributionProtoP\x01ZNgithub.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/telemetry\xf8\x01\x01\xa2\x02\x03\x41UTb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'autonomic.ext.telemetry.distribution_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.autonomic.ext.telemetryB\021DistributionProtoP\001ZNgithub.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/telemetry\370\001\001\242\002\003AUT'
  _globals['_DISTRIBUTION']._serialized_start=72
  _globals['_DISTRIBUTION']._serialized_end=823
  _globals['_DISTRIBUTION_RANGE']._serialized_start=311
  _globals['_DISTRIBUTION_RANGE']._serialized_end=344
  _globals['_DISTRIBUTION_BUCKETOPTIONS']._serialized_start=347
  _globals['_DISTRIBUTION_BUCKETOPTIONS']._serialized_end=823
  _globals['_DISTRIBUTION_BUCKETOPTIONS_LINEAR']._serialized_start=636
  _globals['_DISTRIBUTION_BUCKETOPTIONS_LINEAR']._serialized_end=703
  _globals['_DISTRIBUTION_BUCKETOPTIONS_EXPONENTIAL']._serialized_start=705
  _globals['_DISTRIBUTION_BUCKETOPTIONS_EXPONENTIAL']._serialized_end=784
  _globals['_DISTRIBUTION_BUCKETOPTIONS_EXPLICIT']._serialized_start=786
  _globals['_DISTRIBUTION_BUCKETOPTIONS_EXPLICIT']._serialized_end=812
# @@protoc_insertion_point(module_scope)
