# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: autonomic/ext/telemetry/indicator.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'autonomic/ext/telemetry/indicator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from autonomic.ext.telemetry import well_known_indicators_pb2 as autonomic_dot_ext_dot_telemetry_dot_well__known__indicators__pb2
from autonomic.ext.telemetry.enumerations import indicator_state_pb2 as autonomic_dot_ext_dot_telemetry_dot_enumerations_dot_indicator__state__pb2
from autonomic.ext.telemetry import dtc_pb2 as autonomic_dot_ext_dot_telemetry_dot_dtc__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'autonomic/ext/telemetry/indicator.proto\x12\x17\x61utonomic.ext.telemetry\x1a\x33\x61utonomic/ext/telemetry/well_known_indicators.proto\x1a:autonomic/ext/telemetry/enumerations/indicator_state.proto\x1a!autonomic/ext/telemetry/dtc.proto\x1a\x19google/protobuf/any.proto\"\xff\x02\n\tIndicator\x12U\n\x14well_known_indicator\x18\x01 \x01(\x0e\x32\x35.autonomic.ext.telemetry.indicator.WellKnownIndicatorH\x00\x12%\n\x1bstring_diagnostic_indicator\x18\x02 \x01(\tH\x00\x12\\\n\x0findicator_state\x18\x03 \x01(\x0e\x32\x43.autonomic.ext.telemetry.enumerations.indicatorState.IndicatorState\x12O\n\x17\x64iagnostic_trouble_code\x18\x04 \x01(\x0b\x32..autonomic.ext.telemetry.DiagnosticTroubleCode\x12-\n\x0f\x61\x64\x64itional_info\x18\x05 \x01(\x0b\x32\x14.google.protobuf.AnyB\x16\n\x14\x64iagnostic_indicatorB\xac\x01\n\x1b\x63om.autonomic.ext.telemetryB\x0eIndicatorProtoP\x01ZNgithub.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/telemetry\xf8\x01\x01\xa2\x02\x03\x41UT\xaa\x02!Autonomic.Ext.Telemetry.Indicatorb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'autonomic.ext.telemetry.indicator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.autonomic.ext.telemetryB\016IndicatorProtoP\001ZNgithub.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/telemetry\370\001\001\242\002\003AUT\252\002!Autonomic.Ext.Telemetry.Indicator'
  _globals['_INDICATOR']._serialized_start=244
  _globals['_INDICATOR']._serialized_end=627
# @@protoc_insertion_point(module_scope)
