# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: autonomic/ext/telemetry/raw.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'autonomic/ext/telemetry/raw.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from autonomic.ext.common import oem_data_pb2 as autonomic_dot_ext_dot_common_dot_oem__data__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!autonomic/ext/telemetry/raw.proto\x12\x17\x61utonomic.ext.telemetry\x1a\x1fgoogle/protobuf/timestamp.proto\x1a#autonomic/ext/common/oem_data.proto\"\xfa\x02\n\x0cRawTelemetry\x12\x37\n\x04type\x18\x01 \x01(\x0e\x32).autonomic.ext.telemetry.RawTelemetryType\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x34\n\x10ingest_timestamp\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12H\n\noem_params\x18\x06 \x03(\x0b\x32\x34.autonomic.ext.telemetry.RawTelemetry.OemParamsEntry\x12\x37\n\x08oem_data\x18\x07 \x01(\x0b\x32%.autonomic.ext.common.oemdata.OemData\x12\x14\n\nbytes_data\x18\x14 \x01(\x0cH\x00\x12\x13\n\tjson_data\x18\x15 \x01(\tH\x00\x1a\x30\n\x0eOemParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01:\x02\x18\x01\x42\x06\n\x04\x64\x61ta*\x9f\x01\n\x10RawTelemetryType\x12\x10\n\x0cUNKNOWN_TYPE\x10\x00\x12\r\n\tAU_NATIVE\x10\x01\x12\x07\n\x03MDI\x10\x04\x12\x07\n\x03\x46NV\x10\x02\x12\x08\n\x04\x46TCP\x10\x05\x12\x13\n\x0fPUBLISH_REQUEST\x10\x06\x12\n\n\x06REPORT\x10\x07\x12\x0e\n\nFNV2_MMOTA\x10\x08\x12\x1d\n\x19\x45NCRYPTED_PUBLISH_REQUEST\x10\tB\x8b\x01\n\x1b\x63om.autonomic.ext.telemetryB\x11RawTelemetryProtoP\x01ZNgithub.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/telemetry\xf8\x01\x01\xa2\x02\x03\x41UTb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'autonomic.ext.telemetry.raw_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.autonomic.ext.telemetryB\021RawTelemetryProtoP\001ZNgithub.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/telemetry\370\001\001\242\002\003AUT'
  _globals['_RAWTELEMETRY_OEMPARAMSENTRY']._loaded_options = None
  _globals['_RAWTELEMETRY_OEMPARAMSENTRY']._serialized_options = b'8\001'
  _globals['_RAWTELEMETRY']._loaded_options = None
  _globals['_RAWTELEMETRY']._serialized_options = b'\030\001'
  _globals['_RAWTELEMETRYTYPE']._serialized_start=514
  _globals['_RAWTELEMETRYTYPE']._serialized_end=673
  _globals['_RAWTELEMETRY']._serialized_start=133
  _globals['_RAWTELEMETRY']._serialized_end=511
  _globals['_RAWTELEMETRY_OEMPARAMSENTRY']._serialized_start=451
  _globals['_RAWTELEMETRY_OEMPARAMSENTRY']._serialized_end=499
# @@protoc_insertion_point(module_scope)
