/*-
 * ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
 * Autonomic Proprietary 1.0
 * ——————————————————————————————————————————————————————————————————————————————
 * Copyright (C) 2017 - 2024 Autonomic, LLC - All rights reserved
 * ——————————————————————————————————————————————————————————————————————————————
 * Proprietary and confidential.
 * 
 * NOTICE:  All information contained herein is, and remains the property of
 * Autonomic, LLC and its suppliers, if any.  The intellectual and technical
 * concepts contained herein are proprietary to Autonomic, LLC and its suppliers
 * and may be covered by U.S. and Foreign Patents, patents in process, and are
 * protected by trade secret or copyright law. Dissemination of this information
 * or reproduction of this material is strictly forbidden unless prior written
 * permission is obtained from Autonomic, LLC.
 * 
 * Unauthorized copy of this file, via any medium is strictly prohibited.
 * ______________________________________________________________________________
 */
syntax = "proto3";

package autonomic.ext.asset.enumerations.fuelType;

option go_package = "github.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/asset/enumerations";
option java_package = "com.autonomic.ext.asset.enumerations";
option java_outer_classname = "FuelTypeProto";
option java_multiple_files = true;

option cc_enable_arenas = true;

option objc_class_prefix = "AUT";

enum FuelType {
  GASOLINE = 0;
  HYBRID = 1;
  ELECTRIC = 2;
  DIESEL = 3;
  BIODIESEL = 4;
  FLEXFUEL = 5;
  ETHANOL = 6;
  METHANOL = 7;
  BI_FUEL = 8;
  LPG = 9; // Liquefied Petroleum Gas
  CNG = 10; // Compressed Natural Gas
  NGV = 11; // Natural Gas Vehicle
}
