import Foundation

/// Catalog of pre-recorded voice clips the demo drawer surfaces.
/// Each case maps to a *family* of bundled WAV files (one per
/// persona) under VSACompanion/DemoClips/. Tapping a phrase in
/// the Assistant drawer resolves the right WAV via
/// `fileName(for:)` and streams its PCM bytes through the same
/// WebSocket the live mic uses, so the rest of the session
/// pipeline (ASR, transcript display, Nova reply) doesn't know the
/// audio came from a file rather than a microphone.
///
/// Persona-specific voices (regenerated by
/// scripts/generate-demo-clips.py via Polly neural):
///   fleet  → Joanna  (US English, female)         — Samantha Carter
///   oem    → Matthew (US English, male)           — Marcus Reyes
///   rental → Kajal   (Indian English, female)     — Priya Shah
///
/// Each case's `rawValue` is the filename **stem** (no persona
/// suffix, no extension). The actual WAV resolves to
/// `<stem>-<persona>.wav`.
///
/// To add a new phrase:
///   1. Add a (suffix, text) line in scripts/generate-demo-clips.py
///   2. Run it — generates 3 WAVs (one per persona)
///   3. Add a case here matching the suffix
///   4. Register all 3 new WAVs in the Xcode project
enum DemoClip: String, CaseIterable, Identifiable {
    case tirePressureLow      = "tire-pressure-low"
    case checkEngine          = "check-engine"
    case findServiceCenter    = "find-service-center"
    case yes                  = "yes"
    case yesTuesday           = "yes-tuesday"
    case speakWithAgent       = "speak-with-agent"
    case inflateTireMyself    = "inflate-tire-myself"
    case brakeSoftPedal       = "brake-soft-pedal"
    case recallCheck          = "recall-check"
    case whereNearby          = "where-nearby"
    case tempGaugeRed         = "temp-gauge-red"
    case lastServiced         = "last-serviced"
    case dtcExplainP0420      = "dtc-explain-p0420"
    case engineRough          = "engine-rough"

    var id: String { rawValue }

    /// Resolve the persona-specific WAV filename (without extension).
    /// Falls back to the fleet voice for unknown segments so a
    /// misconfigured tenant still demos with a working clip.
    func fileName(for segment: LayoutSegment) -> String {
        let suffix: String
        switch segment {
        case .oem:    suffix = "oem"
        case .rental: suffix = "rental"
        default:      suffix = "fleet"
        }
        return "\(rawValue)-\(suffix)"
    }

    /// Display label for the drawer button. Kept short so several
    /// phrases fit in a horizontal scroll without truncating.
    var label: String {
        switch self {
        case .tirePressureLow:   return "Tire pressure is low"
        case .checkEngine:       return "Check engine light?"
        case .findServiceCenter: return "Find a service center"
        case .yes:               return "Yes"
        case .yesTuesday:        return "Yes, Tuesday"
        case .speakWithAgent:    return "Speak to an agent"
        case .inflateTireMyself: return "Can I inflate it myself?"
        case .brakeSoftPedal:    return "Brake light + soft pedal"
        case .recallCheck:       return "Recall on my vehicle?"
        case .whereNearby:       return "Where can I get this looked at?"
        case .tempGaugeRed:      return "Temp gauge is red"
        case .lastServiced:      return "When was it last serviced?"
        case .dtcExplainP0420:   return "What does P0420 mean?"
        case .engineRough:       return "Engine running rough"
        }
    }

    /// SF Symbol shown inside each phrase pill.
    var symbolName: String {
        switch self {
        case .tirePressureLow:   return "tire"
        case .checkEngine:       return "exclamationmark.triangle"
        case .findServiceCenter: return "mappin.and.ellipse"
        case .yes:               return "checkmark"
        case .yesTuesday:        return "calendar"
        case .speakWithAgent:    return "person.wave.2"
        case .inflateTireMyself: return "wrench.and.screwdriver"
        case .brakeSoftPedal:    return "brakesignal"
        case .recallCheck:       return "bell.badge"
        case .whereNearby:       return "location.magnifyingglass"
        case .tempGaugeRed:      return "thermometer.high"
        case .lastServiced:      return "clock.arrow.circlepath"
        case .dtcExplainP0420:   return "doc.text.magnifyingglass"
        case .engineRough:       return "engine.combustion"
        }
    }

    /// What the audio clip *says*, in plain text. Kept for the
    /// transcript bubble in the UI (so the demo viewer sees the
    /// phrase as text alongside hearing the audio). NOT sent as a
    /// parallel `text.input` to the backend — Nova Sonic v2 was
    /// observed handling audio + text dual injection unreliably
    /// (one input or the other gets the PARTIAL_TURN marker).
    /// playDemoClip now sends audio-only and trusts Nova's STT.
    /// Phrases are deliberately 1.5s+ with clear sentence breaks
    /// so Nova STT VAD reliably commits an end-of-utterance and
    /// the audio user content closes cleanly.
    var transcriptText: String {
        switch self {
        case .tirePressureLow:   return "My tire pressure is low and I need help with that."
        case .checkEngine:       return "Why is my check engine light on right now?"
        case .findServiceCenter: return "Could you find a nearby service center for me?"
        case .yes:               return "Yes, please go ahead and book that appointment for me."
        case .yesTuesday:        return "Yes, Tuesday at one PM works great for me, please book it."
        case .speakWithAgent:    return "I'd like to speak with a human agent please."
        case .inflateTireMyself: return "Hey, can I just inflate the tire myself instead?"
        case .brakeSoftPedal:    return "My brake light is on and the pedal feels soft."
        case .recallCheck:       return "Is there a recall on my vehicle?"
        case .whereNearby:       return "Where's the nearest place I can get this looked at?"
        case .tempGaugeRed:      return "My temperature gauge is in the red."
        case .lastServiced:      return "When was my truck last serviced?"
        case .dtcExplainP0420:   return "What does code P0420 mean for my truck?"
        case .engineRough:       return "My engine is running really rough and losing power."
        }
    }

    /// Persona-aware list of clips offered in the drawer. OEM and
    /// rental drivers don't need every phrase — surface only the
    /// ones that fit their flow so the drawer stays uncluttered
    /// during a demo.
    static func script(for segment: LayoutSegment) -> [DemoClip] {
        switch segment {
        case .oem:
            // OEM owner: tire issue → service search → yes/booking →
            // optional agent. Skip "find a service center" because
            // OEM flow naturally proposes the dealer; demoing both
            // paths in a row is confusing.
            return [.brakeSoftPedal, .tirePressureLow, .checkEngine, .recallCheck,
                    .inflateTireMyself,
                    .yes, .yesTuesday, .speakWithAgent]
        case .rental:
            // Rental: short trip-driver flow. No "speak to agent" or
            // long booking sequence — the rental persona is meant to
            // show "quick find + go".
            return [.brakeSoftPedal, .tirePressureLow, .findServiceCenter, .inflateTireMyself, .yes]
        default:
            // Fleet: full catalog. Used by the fleet persona
            // demo, exercises the longest path (triage → find →
            // book → escalate) plus the DIY-advisor branch.
            return [.brakeSoftPedal, .recallCheck,
                    .tempGaugeRed, .engineRough, .dtcExplainP0420, .lastServiced,
                    .tirePressureLow, .checkEngine, .findServiceCenter, .whereNearby,
                    .inflateTireMyself,
                    .yes, .yesTuesday, .speakWithAgent]
        }
    }
}

/// A pre-orchestrated demo flow: a short title, one-line description,
/// and an ordered list of clips that tell a coherent story when tapped
/// in sequence. The Demo Phrases drawer renders these as expandable
/// groups so the demoer can talk through "Tire pressure flow" without
/// remembering which pill comes next.
///
/// Scenarios are persona-aware via `DemoScenario.scenarios(for:)`.
/// Adding a new scenario: add a static let here and include it in
/// the appropriate persona switch case below. The scenarios reuse
/// the existing `DemoClip` cases — no new audio assets needed unless
/// the scenario introduces a new utterance.
struct DemoScenario: Identifiable {
    let id: String
    let name: String
    let description: String
    /// SF Symbol shown in the scenario header.
    let symbolName: String
    /// Ordered clips that make up the flow. Tapping the Nth clip plays
    /// only that one — sequencing is the demoer's responsibility, but
    /// the numbered display makes the order obvious.
    let steps: [DemoClip]

    static let tirePressure = DemoScenario(
        id: "tire-pressure",
        name: "Tire Pressure Flow",
        description: "Driver reports low tire → Nova offers service or DIY → driver picks service → finds, books.",
        symbolName: "tire",
        steps: [.tirePressureLow, .findServiceCenter, .yes, .yesTuesday]
    )
    static let dtcCheckEngine = DemoScenario(
        id: "dtc-check-engine",
        name: "Check Engine Light",
        description: "Driver asks about a warning light. Nova explains the active fault.",
        symbolName: "exclamationmark.triangle",
        steps: [.checkEngine]
    )
    static let escalateToAgent = DemoScenario(
        id: "escalate-to-agent",
        name: "Escalate to Agent",
        description: "Driver wants a human. Hands off to fleet support via Connect chat.",
        symbolName: "person.wave.2",
        steps: [.speakWithAgent, .yes]
    )
    static let quickFind = DemoScenario(
        id: "quick-find",
        name: "Quick Service Find",
        description: "Renter asks for a nearby service center; chains-first results.",
        symbolName: "mappin.and.ellipse",
        steps: [.findServiceCenter, .yes]
    )
    static let dealerBooking = DemoScenario(
        id: "oem-dealer-booking",
        name: "Dealer Booking",
        description: "OEM driver routed to authorized brand dealer for tire service (after picking service path).",
        symbolName: "building.2",
        steps: [.tirePressureLow, .findServiceCenter, .yes, .yesTuesday]
    )
    static let diySelfService = DemoScenario(
        id: "diy-self-service",
        name: "Self-Service Path",
        description: "Driver reports low tire → Nova offers service or DIY → driver picks DIY → owner manual guidance.",
        symbolName: "wrench.and.screwdriver",
        steps: [.tirePressureLow, .inflateTireMyself]
    )
    static let brakeEmergency = DemoScenario(
        id: "brake-emergency",
        name: "Brake Failure (P0)",
        description: "Driver reports brake warning light + soft pedal → Nova triages P0 → escalates to a human agent.",
        symbolName: "brakesignal",
        steps: [.brakeSoftPedal]
    )
    static let recallLookup = DemoScenario(
        id: "recall-lookup",
        name: "Recall Lookup",
        description: "Driver asks whether their vehicle has an open recall. Nova checks and explains any active campaign.",
        symbolName: "bell.badge",
        steps: [.recallCheck]
    )
    static let coolantWarning = DemoScenario(
        id: "coolant-warning",
        name: "Coolant / Overheating",
        description: "Driver reports the temperature gauge in the red. Nova triages the overheat risk and steers to the right next step (severity follows the active DTC).",
        symbolName: "thermometer.high",
        steps: [.tempGaugeRed]
    )
    static let findNearby = DemoScenario(
        id: "find-nearby",
        name: "Find Service Nearby",
        description: "Driver asks where to get it looked at. Nova finds the nearest center and books on confirmation.",
        symbolName: "location.magnifyingglass",
        steps: [.whereNearby, .yes, .yesTuesday]
    )
    static let serviceHistory = DemoScenario(
        id: "service-history",
        name: "Service History",
        description: "Driver asks when the truck was last serviced — grounded in this vehicle's own records.",
        symbolName: "clock.arrow.circlepath",
        steps: [.lastServiced]
    )
    static let explainCode = DemoScenario(
        id: "explain-code",
        name: "Explain a Code",
        description: "Driver asks what a diagnostic code means. Nova answers from the OEM knowledge base (grounded, with citations).",
        symbolName: "doc.text.magnifyingglass",
        steps: [.dtcExplainP0420]
    )
    static let engineMisfire = DemoScenario(
        id: "engine-misfire",
        name: "Engine Misfire (P1)",
        description: "Driver reports the engine running rough. With P0300 active, Nova triages P1 — drive with caution, service soon (the mid-tier between stop-driving and monitor).",
        symbolName: "engine.combustion",
        steps: [.engineRough]
    )

    /// Persona-tailored scenario lists. Each persona gets the demos
    /// that match its expected real-world story so the audience sees
    /// flows that make sense for that customer.
    static func scenarios(for segment: LayoutSegment) -> [DemoScenario] {
        switch segment {
        case .oem:
            // OEM emphasizes brand-channel routing: brake-P0 lead,
            // then tire issue → dealer book, recall lookup (very
            // relevant to brand owners), plus check-engine and
            // escalation as service-recovery flows.
            return [.brakeEmergency, .dealerBooking, .recallLookup, .dtcCheckEngine, .diySelfService, .escalateToAgent]
        case .rental:
            // Rental keeps it short: brake-P0 safety lead, quick find,
            // optional DIY for simple fixes, optional escalation.
            // Renters return the car so we skip long booking sequences
            // and the ownership-specific recall lookup.
            return [.brakeEmergency, .quickFind, .diySelfService, .escalateToAgent]
        default:
            // Fleet sees everything; brake-P0 leads (flagship demo),
            // then tire-pressure full-flow, recall lookup, self-service
            // DIY branch, check-engine, and escalation.
            return [.brakeEmergency, .coolantWarning, .engineMisfire, .tirePressure, .findNearby,
                    .recallLookup, .explainCode, .serviceHistory,
                    .diySelfService, .dtcCheckEngine, .escalateToAgent]
        }
    }
}
