# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: autonomic/ext/telemetry/report.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'autonomic/ext/telemetry/report.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from autonomic.ext.telemetry import metric_pb2 as autonomic_dot_ext_dot_telemetry_dot_metric__pb2
from autonomic.ext.telemetry.modules import module_pb2 as autonomic_dot_ext_dot_telemetry_dot_modules_dot_module__pb2
from autonomic.ext.telemetry import report_tag_pb2 as autonomic_dot_ext_dot_telemetry_dot_report__tag__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$autonomic/ext/telemetry/report.proto\x12\x17\x61utonomic.ext.telemetry\x1a$autonomic/ext/telemetry/metric.proto\x1a,autonomic/ext/telemetry/modules/module.proto\x1a(autonomic/ext/telemetry/report_tag.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf9\x01\n\x06Report\x12\x0e\n\x06source\x18\x01 \x01(\t\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x30\n\x07metrics\x18\x03 \x03(\x0b\x32\x1f.autonomic.ext.telemetry.Metric\x12\x30\n\x07modules\x18\x04 \x03(\x0b\x32\x1f.autonomic.ext.telemetry.Module\x12\x30\n\x04tags\x18\x05 \x03(\x0b\x32\".autonomic.ext.telemetry.ReportTag\x12\x1a\n\x12oem_correlation_id\x18\x06 \x01(\tB\x85\x01\n\x1b\x63om.autonomic.ext.telemetryB\x0bReportProtoP\x01ZNgithub.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/telemetry\xf8\x01\x01\xa2\x02\x03\x41UTb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'autonomic.ext.telemetry.report_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.autonomic.ext.telemetryB\013ReportProtoP\001ZNgithub.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/telemetry\370\001\001\242\002\003AUT'
  _globals['_REPORT']._serialized_start=225
  _globals['_REPORT']._serialized_end=474
# @@protoc_insertion_point(module_scope)
