# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: autonomic/ext/telemetry/enumerations/ev_battery_charge_display_status.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'autonomic/ext/telemetry/enumerations/ev_battery_charge_display_status.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nKautonomic/ext/telemetry/enumerations/ev_battery_charge_display_status.proto\x12\x41\x61utonomic.ext.telemetry.enumerations.evBatteryChargeDisplayStatus*\xc8\x01\n\x1c\x45vBatteryChargeDisplayStatus\x12\x0b\n\x07UNKNOWN\x10\x00\x12\r\n\tNOT_READY\x10\x01\x12\x1a\n\x16\x46\x41ULT_UNKNOWN_LOCATION\x10\x02\x12\x14\n\x10\x46\x41ULT_INSIDE_CAR\x10\x03\x12\x15\n\x11\x46\x41ULT_OUTSIDE_CAR\x10\x04\x12\x0f\n\x0bIN_PROGRESS\x10\x05\x12\r\n\tSCHEDULED\x10\x06\x12\x0c\n\x08\x43OMPLETE\x10\x07\x12\x11\n\rFAST_CHARGING\x10\x08\x1a\x02\x18\x01\x42\xb5\x01\n(com.autonomic.ext.telemetry.enumerationsB!EvBatteryChargeDisplayStatusProtoP\x01Z[github.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/telemetry/enumerations\xf8\x01\x01\xa2\x02\x03\x41UTb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'autonomic.ext.telemetry.enumerations.ev_battery_charge_display_status_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n(com.autonomic.ext.telemetry.enumerationsB!EvBatteryChargeDisplayStatusProtoP\001Z[github.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/telemetry/enumerations\370\001\001\242\002\003AUT'
  _globals['_EVBATTERYCHARGEDISPLAYSTATUS']._loaded_options = None
  _globals['_EVBATTERYCHARGEDISPLAYSTATUS']._serialized_options = b'\030\001'
  _globals['_EVBATTERYCHARGEDISPLAYSTATUS']._serialized_start=147
  _globals['_EVBATTERYCHARGEDISPLAYSTATUS']._serialized_end=347
# @@protoc_insertion_point(module_scope)
