# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: autonomic/ext/asset/asset.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'autonomic/ext/asset/asset.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x61utonomic/ext/asset/asset.proto\x12\x13\x61utonomic.ext.asset\"\xbf\x01\n\x10\x41ssetChangeEvent\x12=\n\x04type\x18\x01 \x01(\x0e\x32/.autonomic.ext.asset.AssetChangeEvent.EventType\x12\x38\n\rasset_details\x18\x02 \x01(\x0b\x32!.autonomic.ext.asset.AssetDetails\"2\n\tEventType\x12\x0b\n\x07\x43REATED\x10\x00\x12\x0b\n\x07UPDATED\x10\x01\x12\x0b\n\x07\x44\x45LETED\x10\x02\"\xb3\x04\n\x0c\x41ssetDetails\x12\n\n\x02id\x18\x01 \x01(\t\x12\x39\n\x04type\x18\x02 \x01(\x0e\x32+.autonomic.ext.asset.AssetDetails.AssetType\x12\x45\n\nproperties\x18\x03 \x03(\x0b\x32\x31.autonomic.ext.asset.AssetDetails.PropertiesEntry\x12V\n\x13reported_properties\x18\x04 \x03(\x0b\x32\x39.autonomic.ext.asset.AssetDetails.ReportedPropertiesEntry\x12\x39\n\x04tags\x18\x05 \x03(\x0b\x32+.autonomic.ext.asset.AssetDetails.TagsEntry\x12\x0b\n\x03vin\x18\x06 \x01(\t\x12\x0b\n\x03\x65sn\x18\x07 \x01(\t\x12\x13\n\x0b\x64\x65vice_type\x18\x08 \x01(\t\x12\x12\n\naccount_id\x18\t \x01(\t\x1a\x31\n\x0fPropertiesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a\x39\n\x17ReportedPropertiesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a+\n\tTagsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"$\n\tAssetType\x12\x0b\n\x07VEHICLE\x10\x00\x12\n\n\x06\x44\x45VICE\x10\x01\x42|\n\x17\x63om.autonomic.ext.assetB\nAssetProtoP\x01ZJgithub.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/asset\xf8\x01\x01\xa2\x02\x03\x41UTb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'autonomic.ext.asset.asset_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\027com.autonomic.ext.assetB\nAssetProtoP\001ZJgithub.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/asset\370\001\001\242\002\003AUT'
  _globals['_ASSETDETAILS_PROPERTIESENTRY']._loaded_options = None
  _globals['_ASSETDETAILS_PROPERTIESENTRY']._serialized_options = b'8\001'
  _globals['_ASSETDETAILS_REPORTEDPROPERTIESENTRY']._loaded_options = None
  _globals['_ASSETDETAILS_REPORTEDPROPERTIESENTRY']._serialized_options = b'8\001'
  _globals['_ASSETDETAILS_TAGSENTRY']._loaded_options = None
  _globals['_ASSETDETAILS_TAGSENTRY']._serialized_options = b'8\001'
  _globals['_ASSETCHANGEEVENT']._serialized_start=57
  _globals['_ASSETCHANGEEVENT']._serialized_end=248
  _globals['_ASSETCHANGEEVENT_EVENTTYPE']._serialized_start=198
  _globals['_ASSETCHANGEEVENT_EVENTTYPE']._serialized_end=248
  _globals['_ASSETDETAILS']._serialized_start=251
  _globals['_ASSETDETAILS']._serialized_end=814
  _globals['_ASSETDETAILS_PROPERTIESENTRY']._serialized_start=623
  _globals['_ASSETDETAILS_PROPERTIESENTRY']._serialized_end=672
  _globals['_ASSETDETAILS_REPORTEDPROPERTIESENTRY']._serialized_start=674
  _globals['_ASSETDETAILS_REPORTEDPROPERTIESENTRY']._serialized_end=731
  _globals['_ASSETDETAILS_TAGSENTRY']._serialized_start=733
  _globals['_ASSETDETAILS_TAGSENTRY']._serialized_end=776
  _globals['_ASSETDETAILS_ASSETTYPE']._serialized_start=778
  _globals['_ASSETDETAILS_ASSETTYPE']._serialized_end=814
# @@protoc_insertion_point(module_scope)
