# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: autonomic/ext/command/errors/hardware_state.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'autonomic/ext/command/errors/hardware_state.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from autonomic.ext.telemetry.enumerations import engine_status_pb2 as autonomic_dot_ext_dot_telemetry_dot_enumerations_dot_engine__status__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1autonomic/ext/command/errors/hardware_state.proto\x12\x1c\x61utonomic.ext.command.errors\x1a\x38\x61utonomic/ext/telemetry/enumerations/engine_status.proto\"\x8c\x02\n\rHardwareState\x12W\n\x0c\x65ngine_state\x18\x01 \x01(\x0e\x32?.autonomic.ext.telemetry.enumerations.engineStatus.EngineStatusH\x00\x12J\n\x11\x64oor_handle_state\x18\x02 \x01(\x0e\x32-.autonomic.ext.command.errors.DoorHandleStateH\x00\x12N\n\x13hood_position_state\x18\x03 \x01(\x0e\x32/.autonomic.ext.command.errors.HoodPositionStateH\x00\x42\x06\n\x04type*d\n\x0f\x44oorHandleState\x12\x1d\n\x19UNKNOWN_DOOR_HANDLE_STATE\x10\x00\x12\x18\n\x14\x44OOR_HANDLE_ACTUATED\x10\x01\x12\x18\n\x14\x44OOR_HANDLE_RELEASED\x10\x02*r\n\x11HoodPositionState\x12\x1f\n\x1bUNKNOWN_HOOD_POSITION_STATE\x10\x00\x12\x1c\n\x18HOOD_POSITION_STATE_AJAR\x10\x01\x12\x1e\n\x1aHOOD_POSITION_STATE_CLOSED\x10\x02\x42\x96\x01\n com.autonomic.ext.command.errorsB\x12HardwareStateProtoP\x01ZSgithub.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/command/errors\xf8\x01\x01\xa2\x02\x03\x41UTb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'autonomic.ext.command.errors.hardware_state_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n com.autonomic.ext.command.errorsB\022HardwareStateProtoP\001ZSgithub.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/command/errors\370\001\001\242\002\003AUT'
  _globals['_DOORHANDLESTATE']._serialized_start=412
  _globals['_DOORHANDLESTATE']._serialized_end=512
  _globals['_HOODPOSITIONSTATE']._serialized_start=514
  _globals['_HOODPOSITIONSTATE']._serialized_end=628
  _globals['_HARDWARESTATE']._serialized_start=142
  _globals['_HARDWARESTATE']._serialized_end=410
# @@protoc_insertion_point(module_scope)
