# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: autonomic/ext/cloud/command_request.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'autonomic/ext/cloud/command_request.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from autonomic.ext.command import command_pb2 as autonomic_dot_ext_dot_command_dot_command__pb2
from autonomic.ext.validation import validation_options_pb2 as autonomic_dot_ext_dot_validation_dot_validation__options__pb2
from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)autonomic/ext/cloud/command_request.proto\x12\x1b\x61utonomic.ext.cloud.command\x1a\x1fgoogle/protobuf/timestamp.proto\x1a#autonomic/ext/command/command.proto\x1a\x31\x61utonomic/ext/validation/validation_options.proto\x1a google/protobuf/descriptor.proto\"\x9b\x02\n\x0e\x43ommandRequest\x12\x43\n\x0f\x63ommand_trigger\x18\x01 \x01(\x0b\x32%.autonomic.ext.command.CommandTriggerB\x03\xc8>\x01\x12\x36\n\nexpiration\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x06\xc8>\x01\xd0>\x02\x12\x34\n\x08\x63reation\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x06\xc8>\x01\xd0>\x01\x12\"\n\x1a\x66\x61il_if_commands_precluded\x18\x05 \x01(\x08\x12\x1b\n\x13wakeup_if_necessary\x18\x06 \x01(\x08:\x15\xca>\x12\x61ssets/devices/ecg:@\n\x16permitted_device_types\x12\x1f.google.protobuf.MessageOptions\x18\xe9\x07 \x03(\t:0\n\x08required\x12\x1d.google.protobuf.FieldOptions\x18\xe9\x07 \x01(\x08:j\n\x14timestamp_bound_type\x12\x1d.google.protobuf.FieldOptions\x18\xea\x07 \x01(\x0e\x32,.autonomic.ext.validation.TimestampBoundTypeB\x8d\x01\n\x1f\x63om.autonomic.ext.cloud.commandB\x13\x43ommandRequestProtoP\x01ZJgithub.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/cloud\xf8\x01\x01\xa2\x02\x03\x41UTb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'autonomic.ext.cloud.command_request_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\037com.autonomic.ext.cloud.commandB\023CommandRequestProtoP\001ZJgithub.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/cloud\370\001\001\242\002\003AUT'
  _globals['_COMMANDREQUEST'].fields_by_name['command_trigger']._loaded_options = None
  _globals['_COMMANDREQUEST'].fields_by_name['command_trigger']._serialized_options = b'\310>\001'
  _globals['_COMMANDREQUEST'].fields_by_name['expiration']._loaded_options = None
  _globals['_COMMANDREQUEST'].fields_by_name['expiration']._serialized_options = b'\310>\001\320>\002'
  _globals['_COMMANDREQUEST'].fields_by_name['creation']._loaded_options = None
  _globals['_COMMANDREQUEST'].fields_by_name['creation']._serialized_options = b'\310>\001\320>\001'
  _globals['_COMMANDREQUEST']._loaded_options = None
  _globals['_COMMANDREQUEST']._serialized_options = b'\312>\022assets/devices/ecg'
  _globals['_COMMANDREQUEST']._serialized_start=230
  _globals['_COMMANDREQUEST']._serialized_end=513
# @@protoc_insertion_point(module_scope)
