# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: autonomic/ext/command/hmidisplay/hmi_display.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'autonomic/ext/command/hmidisplay/hmi_display.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2autonomic/ext/command/hmidisplay/hmi_display.proto\x12 autonomic.ext.command.hmidisplay\"\xb3\x01\n\x11HMIDisplayRequest\x12G\n\x0buser_prompt\x18\x01 \x01(\x0b\x32,.autonomic.ext.command.hmidisplay.UserPromptB\x02\x18\x01H\x00\x12\x45\n\nwifi_usage\x18\x02 \x01(\x0b\x32+.autonomic.ext.command.hmidisplay.WifiUsageB\x02\x18\x01H\x00\x42\x0e\n\x0c\x64isplay_info\"\x94\x01\n\nUserPrompt\x12N\n\x0cprompt_scope\x18\x01 \x01(\x0e\x32\x38.autonomic.ext.command.hmidisplay.UserPrompt.PromptScope\"2\n\x0bPromptScope\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x16\n\x12USER_AUTHORIZATION\x10\x01:\x02\x18\x01\"\x8c\x01\n\tWifiUsage\x12I\n\nwifi_scope\x18\x01 \x01(\x0e\x32\x35.autonomic.ext.command.hmidisplay.WifiUsage.WifiScope\"0\n\tWifiScope\x12\x11\n\rUSAGE_WARNING\x10\x00\x12\x10\n\x0cUSAGE_REPORT\x10\x01:\x02\x18\x01\x42\x9b\x01\n$com.autonomic.ext.command.hmidisplayB\x0fHMIDisplayProtoP\x01ZWgithub.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/command/hmidisplay\xf8\x01\x01\xa2\x02\x03\x41UTb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'autonomic.ext.command.hmidisplay.hmi_display_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n$com.autonomic.ext.command.hmidisplayB\017HMIDisplayProtoP\001ZWgithub.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/command/hmidisplay\370\001\001\242\002\003AUT'
  _globals['_HMIDISPLAYREQUEST'].fields_by_name['user_prompt']._loaded_options = None
  _globals['_HMIDISPLAYREQUEST'].fields_by_name['user_prompt']._serialized_options = b'\030\001'
  _globals['_HMIDISPLAYREQUEST'].fields_by_name['wifi_usage']._loaded_options = None
  _globals['_HMIDISPLAYREQUEST'].fields_by_name['wifi_usage']._serialized_options = b'\030\001'
  _globals['_USERPROMPT']._loaded_options = None
  _globals['_USERPROMPT']._serialized_options = b'\030\001'
  _globals['_WIFIUSAGE']._loaded_options = None
  _globals['_WIFIUSAGE']._serialized_options = b'\030\001'
  _globals['_HMIDISPLAYREQUEST']._serialized_start=89
  _globals['_HMIDISPLAYREQUEST']._serialized_end=268
  _globals['_USERPROMPT']._serialized_start=271
  _globals['_USERPROMPT']._serialized_end=419
  _globals['_USERPROMPT_PROMPTSCOPE']._serialized_start=365
  _globals['_USERPROMPT_PROMPTSCOPE']._serialized_end=415
  _globals['_WIFIUSAGE']._serialized_start=422
  _globals['_WIFIUSAGE']._serialized_end=562
  _globals['_WIFIUSAGE_WIFISCOPE']._serialized_start=510
  _globals['_WIFIUSAGE_WIFISCOPE']._serialized_end=558
# @@protoc_insertion_point(module_scope)
