# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: autonomic/ext/command/discovery/discovery.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'autonomic/ext/command/discovery/discovery.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/autonomic/ext/command/discovery/discovery.proto\x12\x1f\x61utonomic.ext.command.discovery\"\x12\n\x10\x44iscoveryRequestB\x98\x01\n#com.autonomic.ext.command.discoveryB\x0e\x44iscoveryProtoP\x01ZVgithub.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/command/discovery\xf8\x01\x01\xa2\x02\x03\x41UTb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'autonomic.ext.command.discovery.discovery_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n#com.autonomic.ext.command.discoveryB\016DiscoveryProtoP\001ZVgithub.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/command/discovery\370\001\001\242\002\003AUT'
  _globals['_DISCOVERYREQUEST']._serialized_start=84
  _globals['_DISCOVERYREQUEST']._serialized_end=102
# @@protoc_insertion_point(module_scope)
