# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: autonomic/ext/common/oem_param.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'autonomic/ext/common/oem_param.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$autonomic/ext/common/oem_param.proto\x12\x1d\x61utonomic.ext.common.oemparam\x1a\x19google/protobuf/any.proto\"\x8c\x01\n\x0eOemSimpleValue\x12\x14\n\nbool_value\x18\x01 \x01(\x08H\x00\x12\x15\n\x0bint64_value\x18\x02 \x01(\x03H\x00\x12\x16\n\x0c\x64ouble_value\x18\x03 \x01(\x01H\x00\x12\x16\n\x0cstring_value\x18\x04 \x01(\tH\x00\x12\x14\n\nbyte_value\x18\x05 \x01(\x0cH\x00\x42\x07\n\x05value\"\xc3\x01\n\x10OemParamValueMap\x12K\n\x06values\x18\x01 \x03(\x0b\x32;.autonomic.ext.common.oemparam.OemParamValueMap.ValuesEntry\x1a\x62\n\x0bValuesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x42\n\x05value\x18\x02 \x01(\x0b\x32\x33.autonomic.ext.common.oemparam.OemParamValueContent:\x02\x38\x01\"X\n\x17RepeatedOemSimpleValues\x12=\n\x06values\x18\x01 \x03(\x0b\x32-.autonomic.ext.common.oemparam.OemSimpleValue\"[\n\x18RepeatedOemParamValueMap\x12?\n\x06values\x18\x01 \x03(\x0b\x32/.autonomic.ext.common.oemparam.OemParamValueMap\"\xef\x02\n\x14OemParamValueContent\x12G\n\x0eoemSimpleValue\x18\x02 \x01(\x0b\x32-.autonomic.ext.common.oemparam.OemSimpleValueH\x00\x12K\n\x10oemParamValueMap\x18\x03 \x01(\x0b\x32/.autonomic.ext.common.oemparam.OemParamValueMapH\x00\x12[\n\x18repeatedOemParamValueMap\x18\x05 \x01(\x0b\x32\x37.autonomic.ext.common.oemparam.RepeatedOemParamValueMapH\x00\x12Y\n\x17repeatedOemSimpleValues\x18\x06 \x01(\x0b\x32\x36.autonomic.ext.common.oemparam.RepeatedOemSimpleValuesH\x00\x42\t\n\x07\x65lementB\x8a\x01\n!com.autonomic.ext.common.oemparamB\rOemParamProtoP\x01ZKgithub.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/common\xf8\x01\x01\xa2\x02\x03\x41UTb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'autonomic.ext.common.oem_param_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n!com.autonomic.ext.common.oemparamB\rOemParamProtoP\001ZKgithub.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/common\370\001\001\242\002\003AUT'
  _globals['_OEMPARAMVALUEMAP_VALUESENTRY']._loaded_options = None
  _globals['_OEMPARAMVALUEMAP_VALUESENTRY']._serialized_options = b'8\001'
  _globals['_OEMSIMPLEVALUE']._serialized_start=99
  _globals['_OEMSIMPLEVALUE']._serialized_end=239
  _globals['_OEMPARAMVALUEMAP']._serialized_start=242
  _globals['_OEMPARAMVALUEMAP']._serialized_end=437
  _globals['_OEMPARAMVALUEMAP_VALUESENTRY']._serialized_start=339
  _globals['_OEMPARAMVALUEMAP_VALUESENTRY']._serialized_end=437
  _globals['_REPEATEDOEMSIMPLEVALUES']._serialized_start=439
  _globals['_REPEATEDOEMSIMPLEVALUES']._serialized_end=527
  _globals['_REPEATEDOEMPARAMVALUEMAP']._serialized_start=529
  _globals['_REPEATEDOEMPARAMVALUEMAP']._serialized_end=620
  _globals['_OEMPARAMVALUECONTENT']._serialized_start=623
  _globals['_OEMPARAMVALUECONTENT']._serialized_end=990
# @@protoc_insertion_point(module_scope)
