# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: autonomic/ext/command/wifi/wifi.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'autonomic/ext/command/wifi/wifi.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%autonomic/ext/command/wifi/wifi.proto\x12\x1a\x61utonomic.ext.command.wifi\"\xaf\x03\n\x13\x41\x63\x63\x65ssPointSettings\x12\x0c\n\x04ssid\x18\x01 \x01(\x0c\x12\x10\n\x08password\x18\x02 \x01(\x0c\x12\x11\n\tbroadcast\x18\x03 \x01(\x08\x12\x64\n\x16wifi_security_protocol\x18\x04 \x01(\x0e\x32\x44.autonomic.ext.command.wifi.AccessPointSettings.WifiSecurityProtocol\x12U\n\x0ewifi_frequency\x18\x05 \x01(\x0e\x32=.autonomic.ext.command.wifi.AccessPointSettings.WifiFrequency\"a\n\x14WifiSecurityProtocol\x12\x1c\n\x18UKNOWN_SECURITY_PROTOCOL\x10\x00\x12\x08\n\x04WPA2\x10\x01\x12\x08\n\x04NONE\x10\x02\x12\r\n\tWPA2_WPA3\x10\x03\x12\x08\n\x04WPA3\x10\x04\"E\n\rWifiFrequency\x12\x1a\n\x16UNKNOWN_WIFI_FREQUENCY\x10\x00\x12\x0b\n\x07GHZ_2_4\x10\x01\x12\x0b\n\x07GHZ_5_0\x10\x02\"\x99\x01\n\x11WifiConfigRequest\x12\x44\n\x0b\x61p_settings\x18\x01 \x01(\x0b\x32/.autonomic.ext.command.wifi.AccessPointSettings\x12>\n\x08\x61p_state\x18\x02 \x01(\x0e\x32,.autonomic.ext.command.wifi.AccessPointState\"\x13\n\x11WifiStatusRequest\"\x9a\x01\n\x12WifiStatusSettings\x12\x44\n\x0b\x61p_settings\x18\x01 \x01(\x0b\x32/.autonomic.ext.command.wifi.AccessPointSettings\x12>\n\x08\x61p_state\x18\x02 \x01(\x0e\x32,.autonomic.ext.command.wifi.AccessPointState*S\n\x10\x41\x63\x63\x65ssPointState\x12\x1e\n\x1aUNKNOWN_ACCESS_POINT_STATE\x10\x00\x12\x0e\n\nAP_ENABLED\x10\x01\x12\x0f\n\x0b\x41P_DISABLED\x10\x02\x42\x89\x01\n\x1e\x63om.autonomic.ext.command.wifiB\tWifiProtoP\x01ZQgithub.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/command/wifi\xf8\x01\x01\xa2\x02\x03\x41UTb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'autonomic.ext.command.wifi.wifi_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\036com.autonomic.ext.command.wifiB\tWifiProtoP\001ZQgithub.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/command/wifi\370\001\001\242\002\003AUT'
  _globals['_ACCESSPOINTSTATE']._serialized_start=837
  _globals['_ACCESSPOINTSTATE']._serialized_end=920
  _globals['_ACCESSPOINTSETTINGS']._serialized_start=70
  _globals['_ACCESSPOINTSETTINGS']._serialized_end=501
  _globals['_ACCESSPOINTSETTINGS_WIFISECURITYPROTOCOL']._serialized_start=333
  _globals['_ACCESSPOINTSETTINGS_WIFISECURITYPROTOCOL']._serialized_end=430
  _globals['_ACCESSPOINTSETTINGS_WIFIFREQUENCY']._serialized_start=432
  _globals['_ACCESSPOINTSETTINGS_WIFIFREQUENCY']._serialized_end=501
  _globals['_WIFICONFIGREQUEST']._serialized_start=504
  _globals['_WIFICONFIGREQUEST']._serialized_end=657
  _globals['_WIFISTATUSREQUEST']._serialized_start=659
  _globals['_WIFISTATUSREQUEST']._serialized_end=678
  _globals['_WIFISTATUSSETTINGS']._serialized_start=681
  _globals['_WIFISTATUSSETTINGS']._serialized_end=835
# @@protoc_insertion_point(module_scope)
