# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: autonomic/ext/command/diagnostic/diagnostic.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'autonomic/ext/command/diagnostic/diagnostic.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from autonomic.ext.common import optional_pb2 as autonomic_dot_ext_dot_common_dot_optional__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1autonomic/ext/command/diagnostic/diagnostic.proto\x12 autonomic.ext.command.diagnostic\x1a#autonomic/ext/common/optional.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x94\x02\n\x11\x44iagnosticRequest\x12\x10\n\x08log_type\x18\x01 \x01(\t\x12\x16\n\x0e\x62ytestream_url\x18\x02 \x01(\t\x12\x41\n\x0blog_options\x18\x03 \x01(\x0b\x32,.autonomic.ext.command.diagnostic.LogOptions\x12\x41\n\x0breport_type\x18\x04 \x01(\x0e\x32,.autonomic.ext.command.diagnostic.ReportType\x12O\n\x12\x64iagnostic_trigger\x18\x05 \x01(\x0b\x32\x33.autonomic.ext.command.diagnostic.DiagnosticTrigger\"\x92\x02\n\nLogOptions\x12\x43\n\x11initial_log_delay\x18\x01 \x01(\x0b\x32(.autonomic.ext.common.entity.IntOptional\x12>\n\x0clog_interval\x18\x02 \x01(\x0b\x32(.autonomic.ext.common.entity.IntOptional\x12>\n\x0cmax_duration\x18\x03 \x01(\x0b\x32(.autonomic.ext.common.entity.IntOptional\x12?\n\rmax_log_count\x18\x04 \x01(\x0b\x32(.autonomic.ext.common.entity.IntOptional\"}\n\x11\x44iagnosticTrigger\x12\x18\n\x10target_module_id\x18\x01 \x01(\x05\x12\x19\n\x11trigger_condition\x18\x02 \x01(\t\x12\x33\n\x0ftrigger_timeout\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp*?\n\nReportType\x12\x18\n\x14UPLOAD_RESULT_TO_URL\x10\x00\x12\x17\n\x13INCLUDE_IN_RESPONSE\x10\x01\x42\x9b\x01\n$com.autonomic.ext.command.diagnosticB\x0f\x44iagnosticProtoP\x01ZWgithub.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/command/diagnostic\xf8\x01\x01\xa2\x02\x03\x41UTb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'autonomic.ext.command.diagnostic.diagnostic_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n$com.autonomic.ext.command.diagnosticB\017DiagnosticProtoP\001ZWgithub.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/command/diagnostic\370\001\001\242\002\003AUT'
  _globals['_REPORTTYPE']._serialized_start=840
  _globals['_REPORTTYPE']._serialized_end=903
  _globals['_DIAGNOSTICREQUEST']._serialized_start=158
  _globals['_DIAGNOSTICREQUEST']._serialized_end=434
  _globals['_LOGOPTIONS']._serialized_start=437
  _globals['_LOGOPTIONS']._serialized_end=711
  _globals['_DIAGNOSTICTRIGGER']._serialized_start=713
  _globals['_DIAGNOSTICTRIGGER']._serialized_end=838
# @@protoc_insertion_point(module_scope)
