"""
Autonomous Monitoring System

The agent proactively monitors vehicle health and makes autonomous decisions
without relying solely on external anomaly detection systems.
"""

import asyncio
import logging
from datetime import datetime, timedelta
from typing import Dict, List, Optional, Any, Tuple
from dataclasses import dataclass
from enum import Enum

from .hot_path_processor import HotPathProcessor, TelemetryEvent, ActionUrgency
from .agentic_behaviors import AgentGoal, AgentMemory

logger = logging.getLogger(__name__)


class MonitoringStrategy(Enum):
    CONTINUOUS = "continuous"           # Real-time streaming analysis
    ADAPTIVE_POLLING = "adaptive"       # Frequency based on risk level
    PATTERN_BASED = "pattern_based"     # Triggered by learned patterns
    PREDICTIVE = "predictive"           # Based on ML predictions


@dataclass
class VehicleMonitoringProfile:
    """Individual vehicle monitoring configuration"""
    vehicle_id: str
    risk_level: str
    monitoring_frequency: timedelta
    critical_thresholds: Dict[str, float]
    learned_patterns: List[Dict[str, Any]]
    prediction_horizon: timedelta
    last_analysis: datetime
    monitoring_strategy: MonitoringStrategy


@dataclass
class AutonomousAlert:
    """Alert generated by autonomous monitoring"""
    alert_id: str
    vehicle_id: str
    component_type: str
    alert_type: str
    severity: str
    confidence: float
    predicted_failure_time: Optional[datetime]
    reasoning: List[str]
    recommended_actions: List[str]
    created_at: datetime


class AutonomousMonitoringSystem:
    """
    Proactive monitoring system that doesn't rely on external anomaly detection
    """
    
    def __init__(self, config: Dict[str, Any]):
        self.config = config
        self.hot_path_processor = HotPathProcessor(config.get('hot_path', {}))
        self.monitoring_profiles: Dict[str, VehicleMonitoringProfile] = {}
        
        # Autonomous monitoring parameters
        self.base_monitoring_interval = timedelta(seconds=config.get('base_interval_seconds', 30))
        self.high_risk_interval = timedelta(seconds=config.get('high_risk_interval_seconds', 10))
        self.pattern_detection_window = timedelta(hours=config.get('pattern_window_hours', 24))
        
        # ML-based thresholds (learned and adaptive)
        self.adaptive_thresholds: Dict[str, Dict[str, float]] = {}
        
        # Monitoring tasks
        self.monitoring_tasks: Dict[str, asyncio.Task] = {}
        self.pattern_analysis_task: Optional[asyncio.Task] = None
        
        logger.info("Autonomous Monitoring System initialized")
    
    async def start_autonomous_monitoring(self):
        """Start autonomous monitoring for all vehicles"""
        
        logger.info("Starting autonomous monitoring system")
        
        # Start pattern analysis task
        self.pattern_analysis_task = asyncio.create_task(self._continuous_pattern_analysis())
        
        # Start individual vehicle monitoring
        active_vehicles = await self._get_active_vehicles()
        
        for vehicle_id in active_vehicles:
            await self._start_vehicle_monitoring(vehicle_id)
        
        # Start fleet-level monitoring
        asyncio.create_task(self._fleet_health_monitoring())
        
        logger.info(f"Autonomous monitoring started for {len(active_vehicles)} vehicles")
    
    async def _start_vehicle_monitoring(self, vehicle_id: str):
        """Start autonomous monitoring for a specific vehicle"""
        
        # Create or update monitoring profile
        profile = await self._create_monitoring_profile(vehicle_id)
        self.monitoring_profiles[vehicle_id] = profile
        
        # Start monitoring task based on strategy
        if profile.monitoring_strategy == MonitoringStrategy.CONTINUOUS:
            task = asyncio.create_task(self._continuous_vehicle_monitoring(vehicle_id))
        elif profile.monitoring_strategy == MonitoringStrategy.ADAPTIVE_POLLING:
            task = asyncio.create_task(self._adaptive_vehicle_monitoring(vehicle_id))
        elif profile.monitoring_strategy == MonitoringStrategy.PATTERN_BASED:
            task = asyncio.create_task(self._pattern_based_monitoring(vehicle_id))
        else:  # PREDICTIVE
            task = asyncio.create_task(self._predictive_vehicle_monitoring(vehicle_id))
        
        self.monitoring_tasks[vehicle_id] = task
        
        logger.info(f"Started {profile.monitoring_strategy.value} monitoring for {vehicle_id}")
    
    async def _continuous_vehicle_monitoring(self, vehicle_id: str):
        """Continuous real-time monitoring of vehicle health"""
        
        profile = self.monitoring_profiles[vehicle_id]
        
        while True:
            try:
                # Get latest telemetry
                telemetry = await self._get_latest_telemetry(vehicle_id)
                
                if telemetry:
                    # Autonomous analysis
                    alerts = await self._autonomous_health_analysis(vehicle_id, telemetry, profile)
                    
                    # Process any alerts
                    for alert in alerts:
                        await self._process_autonomous_alert(alert)
                    
                    # Update monitoring profile based on findings
                    await self._update_monitoring_profile(vehicle_id, telemetry, alerts)
                
                # Dynamic sleep based on risk level
                sleep_duration = self._calculate_monitoring_interval(profile)
                await asyncio.sleep(sleep_duration.total_seconds())
                
            except Exception as e:
                logger.error(f"Error in continuous monitoring for {vehicle_id}: {str(e)}")
                await asyncio.sleep(60)  # Fallback interval
    
    async def _autonomous_health_analysis(self, vehicle_id: str, telemetry: Dict[str, Any], 
                                        profile: VehicleMonitoringProfile) -> List[AutonomousAlert]:
        """
        Autonomous analysis of vehicle health without external triggers
        """
        
        alerts = []
        
        # 1. Threshold-based analysis with adaptive thresholds
        threshold_alerts = await self._adaptive_threshold_analysis(vehicle_id, telemetry, profile)
        alerts.extend(threshold_alerts)
        
        # 2. Trend analysis
        trend_alerts = await self._trend_analysis(vehicle_id, telemetry, profile)
        alerts.extend(trend_alerts)
        
        # 3. Pattern recognition
        pattern_alerts = await self._pattern_recognition_analysis(vehicle_id, telemetry, profile)
        alerts.extend(pattern_alerts)
        
        # 4. Predictive analysis
        predictive_alerts = await self._predictive_failure_analysis(vehicle_id, telemetry, profile)
        alerts.extend(predictive_alerts)
        
        # 5. Cross-component correlation analysis
        correlation_alerts = await self._cross_component_analysis(vehicle_id, telemetry, profile)
        alerts.extend(correlation_alerts)
        
        return alerts
    
    async def _adaptive_threshold_analysis(self, vehicle_id: str, telemetry: Dict[str, Any], 
                                         profile: VehicleMonitoringProfile) -> List[AutonomousAlert]:
        """Analyze telemetry against adaptive thresholds"""
        
        alerts = []
        
        # Get adaptive thresholds for this vehicle
        vehicle_thresholds = self.adaptive_thresholds.get(vehicle_id, {})
        
        # Tire analysis
        if 'tire' in telemetry:
            tire_alerts = await self._analyze_tire_thresholds(vehicle_id, telemetry['tire'], vehicle_thresholds)
            alerts.extend(tire_alerts)
        
        # Engine analysis
        if 'engine' in telemetry:
            engine_alerts = await self._analyze_engine_thresholds(vehicle_id, telemetry['engine'], vehicle_thresholds)
            alerts.extend(engine_alerts)
        
        # Brake analysis
        if 'brake' in telemetry:
            brake_alerts = await self._analyze_brake_thresholds(vehicle_id, telemetry['brake'], vehicle_thresholds)
            alerts.extend(brake_alerts)
        
        return alerts
    
    async def _analyze_tire_thresholds(self, vehicle_id: str, tire_data: Dict[str, Any], 
                                     thresholds: Dict[str, float]) -> List[AutonomousAlert]:
        """Analyze tire data against adaptive thresholds"""
        
        alerts = []
        
        # Get learned thresholds or use defaults
        pressure_critical = thresholds.get('tire_pressure_critical', 1800)
        pressure_warning = thresholds.get('tire_pressure_warning', 2000)
        temp_critical = thresholds.get('tire_temp_critical', 80)
        temp_warning = thresholds.get('tire_temp_warning', 70)
        
        if 'tires' in tire_data:
            for tire in tire_data['tires']:
                position = tire.get('position', 'unknown')
                pressure = tire.get('pressure_mbar', 2200)
                temperature = tire.get('temperature_celsius', 40)
                
                # Pressure analysis
                if pressure < pressure_critical:
                    alerts.append(AutonomousAlert(
                        alert_id=f"auto_{vehicle_id}_{position}_pressure_{int(datetime.utcnow().timestamp())}",
                        vehicle_id=vehicle_id,
                        component_type='tire',
                        alert_type='pressure_critical',
                        severity='critical',
                        confidence=0.95,
                        predicted_failure_time=datetime.utcnow() + timedelta(minutes=30),
                        reasoning=[
                            f"Tire pressure {pressure} mbar below critical threshold {pressure_critical}",
                            f"Position: {position}",
                            "Immediate intervention required"
                        ],
                        recommended_actions=['immediate_stop', 'emergency_service'],
                        created_at=datetime.utcnow()
                    ))
                elif pressure < pressure_warning:
                    alerts.append(AutonomousAlert(
                        alert_id=f"auto_{vehicle_id}_{position}_pressure_{int(datetime.utcnow().timestamp())}",
                        vehicle_id=vehicle_id,
                        component_type='tire',
                        alert_type='pressure_low',
                        severity='high',
                        confidence=0.85,
                        predicted_failure_time=datetime.utcnow() + timedelta(hours=4),
                        reasoning=[
                            f"Tire pressure {pressure} mbar below warning threshold {pressure_warning}",
                            f"Position: {position}",
                            "Schedule maintenance soon"
                        ],
                        recommended_actions=['route_to_service', 'enhanced_monitoring'],
                        created_at=datetime.utcnow()
                    ))
                
                # Temperature analysis
                if temperature > temp_critical:
                    alerts.append(AutonomousAlert(
                        alert_id=f"auto_{vehicle_id}_{position}_temp_{int(datetime.utcnow().timestamp())}",
                        vehicle_id=vehicle_id,
                        component_type='tire',
                        alert_type='temperature_critical',
                        severity='critical',
                        confidence=0.9,
                        predicted_failure_time=datetime.utcnow() + timedelta(minutes=15),
                        reasoning=[
                            f"Tire temperature {temperature}°C above critical threshold {temp_critical}°C",
                            f"Position: {position}",
                            "Risk of tire failure"
                        ],
                        recommended_actions=['immediate_stop', 'cool_down_period'],
                        created_at=datetime.utcnow()
                    ))
        
        return alerts
    
    async def _trend_analysis(self, vehicle_id: str, telemetry: Dict[str, Any], 
                            profile: VehicleMonitoringProfile) -> List[AutonomousAlert]:
        """Analyze trends in telemetry data"""
        
        alerts = []
        
        # Get historical data for trend analysis
        historical_data = await self._get_historical_telemetry(vehicle_id, hours=24)
        
        if len(historical_data) < 10:  # Need sufficient data points
            return alerts
        
        # Analyze tire pressure trends
        if 'tire' in telemetry:
            tire_trend_alerts = await self._analyze_tire_trends(vehicle_id, historical_data, telemetry)
            alerts.extend(tire_trend_alerts)
        
        return alerts
    
    async def _analyze_tire_trends(self, vehicle_id: str, historical_data: List[Dict], 
                                 current_telemetry: Dict[str, Any]) -> List[AutonomousAlert]:
        """Analyze tire pressure and temperature trends"""
        
        alerts = []
        
        # Extract tire pressure trends
        pressure_trends = {}
        
        for data_point in historical_data:
            timestamp = datetime.fromisoformat(data_point.get('timestamp', ''))
            tire_data = data_point.get('tire', {})
            
            if 'tires' in tire_data:
                for tire in tire_data['tires']:
                    position = tire.get('position')
                    pressure = tire.get('pressure_mbar')
                    
                    if position and pressure:
                        if position not in pressure_trends:
                            pressure_trends[position] = []
                        pressure_trends[position].append((timestamp, pressure))
        
        # Analyze trends for each tire position
        for position, trend_data in pressure_trends.items():
            if len(trend_data) >= 5:  # Minimum points for trend analysis
                # Sort by timestamp
                trend_data.sort(key=lambda x: x[0])
                
                # Calculate pressure drop rate
                recent_points = trend_data[-5:]  # Last 5 points
                if len(recent_points) >= 2:
                    time_span = (recent_points[-1][0] - recent_points[0][0]).total_seconds() / 3600  # hours
                    pressure_drop = recent_points[0][1] - recent_points[-1][1]  # mbar
                    
                    if time_span > 0:
                        drop_rate = pressure_drop / time_span  # mbar per hour
                        
                        # Alert if pressure dropping rapidly
                        if drop_rate > 50:  # > 50 mbar/hour
                            predicted_failure = datetime.utcnow() + timedelta(hours=max(1, (recent_points[-1][1] - 1800) / drop_rate))
                            
                            alerts.append(AutonomousAlert(
                                alert_id=f"trend_{vehicle_id}_{position}_{int(datetime.utcnow().timestamp())}",
                                vehicle_id=vehicle_id,
                                component_type='tire',
                                alert_type='pressure_trend_declining',
                                severity='high',
                                confidence=0.8,
                                predicted_failure_time=predicted_failure,
                                reasoning=[
                                    f"Tire pressure dropping at {drop_rate:.1f} mbar/hour",
                                    f"Position: {position}",
                                    f"Current pressure: {recent_points[-1][1]} mbar",
                                    "Trend indicates potential leak or damage"
                                ],
                                recommended_actions=['inspect_tire', 'schedule_maintenance'],
                                created_at=datetime.utcnow()
                            ))
        
        return alerts
    
    async def _pattern_recognition_analysis(self, vehicle_id: str, telemetry: Dict[str, Any], 
                                          profile: VehicleMonitoringProfile) -> List[AutonomousAlert]:
        """Recognize learned failure patterns"""
        
        alerts = []
        
        # Get learned patterns for this vehicle or similar vehicles
        learned_patterns = profile.learned_patterns
        
        for pattern in learned_patterns:
            if await self._matches_failure_pattern(telemetry, pattern):
                confidence = pattern.get('confidence', 0.7)
                
                alerts.append(AutonomousAlert(
                    alert_id=f"pattern_{vehicle_id}_{pattern['pattern_id']}_{int(datetime.utcnow().timestamp())}",
                    vehicle_id=vehicle_id,
                    component_type=pattern['component_type'],
                    alert_type='pattern_match',
                    severity=pattern['severity'],
                    confidence=confidence,
                    predicted_failure_time=datetime.utcnow() + timedelta(hours=pattern.get('time_to_failure_hours', 24)),
                    reasoning=[
                        f"Matches learned failure pattern: {pattern['description']}",
                        f"Pattern confidence: {confidence:.2f}",
                        f"Historical outcomes: {pattern.get('historical_outcomes', 'unknown')}"
                    ],
                    recommended_actions=pattern.get('recommended_actions', ['schedule_maintenance']),
                    created_at=datetime.utcnow()
                ))
        
        return alerts
    
    async def _predictive_failure_analysis(self, vehicle_id: str, telemetry: Dict[str, Any], 
                                         profile: VehicleMonitoringProfile) -> List[AutonomousAlert]:
        """Use ML models to predict failures"""
        
        alerts = []
        
        # Call tire prediction model if tire data available
        if 'tire' in telemetry:
            tire_predictions = await self._call_tire_prediction_model(vehicle_id, telemetry['tire'])
            
            if tire_predictions and tire_predictions.get('failure_probability', 0) > 0.7:
                alerts.append(AutonomousAlert(
                    alert_id=f"ml_{vehicle_id}_tire_{int(datetime.utcnow().timestamp())}",
                    vehicle_id=vehicle_id,
                    component_type='tire',
                    alert_type='ml_prediction',
                    severity='high' if tire_predictions['failure_probability'] > 0.8 else 'medium',
                    confidence=tire_predictions.get('confidence', 0.8),
                    predicted_failure_time=tire_predictions.get('predicted_failure_date'),
                    reasoning=[
                        f"ML model predicts {tire_predictions['failure_probability']:.1%} failure probability",
                        f"Primary failure mode: {tire_predictions.get('failure_mode', 'unknown')}",
                        f"Model confidence: {tire_predictions.get('confidence', 0.8):.2f}"
                    ],
                    recommended_actions=tire_predictions.get('parts_needed', ['inspect_tires']),
                    created_at=datetime.utcnow()
                ))
        
        return alerts
    
    async def _process_autonomous_alert(self, alert: AutonomousAlert):
        """Process an autonomously generated alert"""
        
        logger.info(f"Processing autonomous alert: {alert.alert_type} for {alert.vehicle_id}")
        
        # Convert to telemetry event for hot path processing
        telemetry_event = TelemetryEvent(
            vehicle_id=alert.vehicle_id,
            device_id=alert.vehicle_id,
            component_type=alert.component_type,
            trigger_type=alert.alert_type,
            urgency=alert.severity,
            component_position='unknown',
            timestamp=alert.created_at.isoformat(),
            telemetry_snapshot={
                'alert_confidence': alert.confidence,
                'predicted_failure_time': alert.predicted_failure_time.isoformat() if alert.predicted_failure_time else None,
                'reasoning': alert.reasoning
            },
            source='autonomous_monitoring'
        )
        
        # Process through hot path
        decision = await self.hot_path_processor.process_telemetry_event(telemetry_event)
        
        logger.info(f"Autonomous alert processed, decision: {decision.selected_option['action_type']}")
    
    async def _continuous_pattern_analysis(self):
        """Continuously analyze patterns across the fleet"""
        
        while True:
            try:
                # Analyze patterns across all monitored vehicles
                fleet_patterns = await self._analyze_fleet_patterns()
                
                # Update learned patterns
                await self._update_learned_patterns(fleet_patterns)
                
                # Update adaptive thresholds
                await self._update_adaptive_thresholds(fleet_patterns)
                
                # Sleep for pattern analysis interval
                await asyncio.sleep(3600)  # 1 hour
                
            except Exception as e:
                logger.error(f"Error in pattern analysis: {str(e)}")
                await asyncio.sleep(600)  # 10 minutes fallback
    
    # Helper methods
    async def _get_active_vehicles(self) -> List[str]:
        """Get list of active vehicles to monitor"""
        # In production, query from CMS platform
        return ['VEHICLE-001', 'VEHICLE-002', 'VEHICLE-003']
    
    async def _get_latest_telemetry(self, vehicle_id: str) -> Optional[Dict[str, Any]]:
        """Get latest telemetry for a vehicle"""
        # In production, query Redis cache or DynamoDB
        return {
            'vehicle_id': vehicle_id,
            'timestamp': datetime.utcnow().isoformat(),
            'tire': {
                'tires': [
                    {
                        'position': 'FL',
                        'pressure_mbar': 2100,
                        'temperature_celsius': 45
                    }
                ]
            }
        }
    
    async def _create_monitoring_profile(self, vehicle_id: str) -> VehicleMonitoringProfile:
        """Create monitoring profile for a vehicle"""
        
        # Get vehicle risk assessment
        risk_level = await self._assess_vehicle_risk(vehicle_id)
        
        # Determine monitoring strategy
        if risk_level == 'critical':
            strategy = MonitoringStrategy.CONTINUOUS
            frequency = self.high_risk_interval
        elif risk_level == 'high':
            strategy = MonitoringStrategy.ADAPTIVE_POLLING
            frequency = timedelta(seconds=60)
        else:
            strategy = MonitoringStrategy.PATTERN_BASED
            frequency = self.base_monitoring_interval
        
        return VehicleMonitoringProfile(
            vehicle_id=vehicle_id,
            risk_level=risk_level,
            monitoring_frequency=frequency,
            critical_thresholds={},
            learned_patterns=[],
            prediction_horizon=timedelta(hours=24),
            last_analysis=datetime.utcnow(),
            monitoring_strategy=strategy
        )
    
    async def _assess_vehicle_risk(self, vehicle_id: str) -> str:
        """Assess vehicle risk level"""
        # In production, use ML model or rule-based assessment
        return 'medium'
    
    def _calculate_monitoring_interval(self, profile: VehicleMonitoringProfile) -> timedelta:
        """Calculate dynamic monitoring interval based on risk"""
        
        base_interval = profile.monitoring_frequency
        
        # Adjust based on risk level
        if profile.risk_level == 'critical':
            return base_interval
        elif profile.risk_level == 'high':
            return base_interval * 2
        else:
            return base_interval * 4