# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: autonomic/ext/telemetry/enumerations/diesel_exhaust_filter.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'autonomic/ext/telemetry/enumerations/diesel_exhaust_filter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n@autonomic/ext/telemetry/enumerations/diesel_exhaust_filter.proto\x12\x38\x61utonomic.ext.telemetry.enumerations.dieselExhaustFilter*\x84\x01\n\x13\x44ieselExhaustFilter\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x14\n\x10NORMAL_OPERATION\x10\x01\x12\x0e\n\nOVERLOADED\x10\x02\x12\x1c\n\x14\x43LEANING_IN_PROGRESS\x10\x03\x1a\x02\x08\x01\x12\x0c\n\x08\x41T_LIMIT\x10\x04\x12\x0e\n\nOVER_LIMIT\x10\x05\x42\xac\x01\n(com.autonomic.ext.telemetry.enumerationsB\x18\x44ieselExhaustFilterProtoP\x01Z[github.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/telemetry/enumerations\xf8\x01\x01\xa2\x02\x03\x41UTb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'autonomic.ext.telemetry.enumerations.diesel_exhaust_filter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n(com.autonomic.ext.telemetry.enumerationsB\030DieselExhaustFilterProtoP\001Z[github.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/telemetry/enumerations\370\001\001\242\002\003AUT'
  _globals['_DIESELEXHAUSTFILTER'].values_by_name["CLEANING_IN_PROGRESS"]._loaded_options = None
  _globals['_DIESELEXHAUSTFILTER'].values_by_name["CLEANING_IN_PROGRESS"]._serialized_options = b'\010\001'
  _globals['_DIESELEXHAUSTFILTER']._serialized_start=127
  _globals['_DIESELEXHAUSTFILTER']._serialized_end=259
# @@protoc_insertion_point(module_scope)
