# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: autonomic/ext/telemetry/enumerations/engine_service_indicator.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'autonomic/ext/telemetry/enumerations/engine_service_indicator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nCautonomic/ext/telemetry/enumerations/engine_service_indicator.proto\x12\x1f\x61utonomic.ext.telemetry.signals*-\n\x16\x45ngineServiceIndicator\x12\x07\n\x03OFF\x10\x00\x12\x06\n\x02ON\x10\x01\x1a\x02\x18\x01\x42\xaa\x01\n#com.autonomic.ext.telemetry.signalsB\x1b\x45ngineServiceIndicatorProtoP\x01Z[github.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/telemetry/enumerations\xf8\x01\x01\xa2\x02\x03\x41UTb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'autonomic.ext.telemetry.enumerations.engine_service_indicator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n#com.autonomic.ext.telemetry.signalsB\033EngineServiceIndicatorProtoP\001Z[github.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/telemetry/enumerations\370\001\001\242\002\003AUT'
  _globals['_ENGINESERVICEINDICATOR']._loaded_options = None
  _globals['_ENGINESERVICEINDICATOR']._serialized_options = b'\030\001'
  _globals['_ENGINESERVICEINDICATOR']._serialized_start=104
  _globals['_ENGINESERVICEINDICATOR']._serialized_end=149
# @@protoc_insertion_point(module_scope)
