# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: autonomic/ext/telemetry/enumerations/hybrid_vehicle_mode_status.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'autonomic/ext/telemetry/enumerations/hybrid_vehicle_mode_status.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nEautonomic/ext/telemetry/enumerations/hybrid_vehicle_mode_status.proto\x12<autonomic.ext.telemetry.enumerations.hybridVehicleModeStatus*\xe1\x01\n\x17HybridVehicleModeStatus\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x17\n\x13\x41UTO_CHARGE_DEPLETE\x10\x01\x12\x17\n\x13\x41UTO_CHARGE_SUSTAIN\x10\x02\x12\x19\n\x15\x46ORCED_CHARGE_SUSTAIN\x10\x03\x12\x13\n\x0f\x46ORCED_ELECTRIC\x10\x04\x12\x17\n\x13\x46ORCED_NON_ELECTRIC\x10\x05\x12\x1c\n\x18TEMPORARY_CHARGE_SUSTAIN\x10\x06\x12 \n\x1cPRIORITIZE_CHARGE_GENERATION\x10\x07\x42\xb0\x01\n(com.autonomic.ext.telemetry.enumerationsB\x1cHybridVehicleModeStatusProtoP\x01Z[github.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/telemetry/enumerations\xf8\x01\x01\xa2\x02\x03\x41UTb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'autonomic.ext.telemetry.enumerations.hybrid_vehicle_mode_status_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n(com.autonomic.ext.telemetry.enumerationsB\034HybridVehicleModeStatusProtoP\001Z[github.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/telemetry/enumerations\370\001\001\242\002\003AUT'
  _globals['_HYBRIDVEHICLEMODESTATUS']._serialized_start=136
  _globals['_HYBRIDVEHICLEMODESTATUS']._serialized_end=361
# @@protoc_insertion_point(module_scope)
