# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: autonomic/ext/vehicledeviceregistration/vehicle_device_registration_event.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'autonomic/ext/vehicledeviceregistration/vehicle_device_registration_event.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nOautonomic/ext/vehicledeviceregistration/vehicle_device_registration_event.proto\x12\'autonomic.ext.vehicledeviceregistration\x1a\x1fgoogle/protobuf/timestamp.proto\"\x97\x06\n\x1eVehicleDeviceRegistrationEvent\x12\n\n\x02id\x18\x01 \x01(\t\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x12\n\nbytes_data\x18\x03 \x01(\x0c\x12\x0b\n\x03vin\x18\x04 \x01(\t\x12\x1c\n\x14\x64\x65vice_serial_number\x18\x05 \x01(\t\x12%\n\x1dpre_swap_device_serial_number\x18\t \x01(\t\x12\x13\n\x0b\x64\x65vice_type\x18\x06 \x01(\t\x12\x13\n\x0bregion_code\x18\n \x01(\t\x12\x14\n\x0c\x63ountry_code\x18\x0b \x01(\t\x12g\n\x08metadata\x18\x0c \x03(\x0b\x32U.autonomic.ext.vehicledeviceregistration.VehicleDeviceRegistrationEvent.MetadataEntry\x12^\n\x06status\x18\x07 \x01(\x0e\x32N.autonomic.ext.vehicledeviceregistration.VehicleDeviceRegistrationEvent.Status\x12\x10\n\x08home_url\x18\r \x01(\t\x12i\n\x0c\x66\x61ilure_code\x18\x08 \x01(\x0e\x32S.autonomic.ext.vehicledeviceregistration.VehicleDeviceRegistrationEvent.FailureCode\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"6\n\x06Status\x12\x12\n\x0eUNKNOWN_STATUS\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\x0b\n\x07\x46\x41ILURE\x10\x02\"e\n\x0b\x46\x61ilureCode\x12\x13\n\x0fUNKNOWN_FAILURE\x10\x00\x12\x0f\n\x0bPARSE_ERROR\x10\x01\x12\x14\n\x10\x44\x45VICE_NOT_FOUND\x10\x02\x12\x1a\n\x16INTERNAL_SERVICE_ERROR\x10\x03\x42\xbd\x01\n+com.autonomic.ext.vehicledeviceregistrationB#VehicleDeviceRegistrationEventProtoP\x01Z^github.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/vehicledeviceregistration\xf8\x01\x01\xa2\x02\x03\x41UTb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'autonomic.ext.vehicledeviceregistration.vehicle_device_registration_event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n+com.autonomic.ext.vehicledeviceregistrationB#VehicleDeviceRegistrationEventProtoP\001Z^github.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/vehicledeviceregistration\370\001\001\242\002\003AUT'
  _globals['_VEHICLEDEVICEREGISTRATIONEVENT_METADATAENTRY']._loaded_options = None
  _globals['_VEHICLEDEVICEREGISTRATIONEVENT_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_VEHICLEDEVICEREGISTRATIONEVENT']._serialized_start=158
  _globals['_VEHICLEDEVICEREGISTRATIONEVENT']._serialized_end=949
  _globals['_VEHICLEDEVICEREGISTRATIONEVENT_METADATAENTRY']._serialized_start=743
  _globals['_VEHICLEDEVICEREGISTRATIONEVENT_METADATAENTRY']._serialized_end=790
  _globals['_VEHICLEDEVICEREGISTRATIONEVENT_STATUS']._serialized_start=792
  _globals['_VEHICLEDEVICEREGISTRATIONEVENT_STATUS']._serialized_end=846
  _globals['_VEHICLEDEVICEREGISTRATIONEVENT_FAILURECODE']._serialized_start=848
  _globals['_VEHICLEDEVICEREGISTRATIONEVENT_FAILURECODE']._serialized_end=949
# @@protoc_insertion_point(module_scope)
