# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: autonomic/ext/command/hmiapplication/hmi_application.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'autonomic/ext/command/hmiapplication/hmi_application.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n:autonomic/ext/command/hmiapplication/hmi_application.proto\x12$autonomic.ext.command.hmiapplication\"\xe1\x01\n\x15HMIApplicationMessage\x12\x64\n\x0cpayload_type\x18\x01 \x01(\x0e\x32N.autonomic.ext.command.hmiapplication.HMIApplicationMessage.MessagePayloadType\x12\x18\n\x10hmi_message_type\x18\x02 \x01(\t\"H\n\x12MessagePayloadType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x11\n\rCLOUD_REQUEST\x10\x01\x12\x12\n\x0e\x43LOUD_RESPONSE\x10\x02\x42\xa7\x01\n(com.autonomic.ext.command.hmiapplicationB\x13HMIApplicationProtoP\x01Z[github.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/command/hmiapplication\xf8\x01\x01\xa2\x02\x03\x41UTb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'autonomic.ext.command.hmiapplication.hmi_application_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n(com.autonomic.ext.command.hmiapplicationB\023HMIApplicationProtoP\001Z[github.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/command/hmiapplication\370\001\001\242\002\003AUT'
  _globals['_HMIAPPLICATIONMESSAGE']._serialized_start=101
  _globals['_HMIAPPLICATIONMESSAGE']._serialized_end=326
  _globals['_HMIAPPLICATIONMESSAGE_MESSAGEPAYLOADTYPE']._serialized_start=254
  _globals['_HMIAPPLICATIONMESSAGE_MESSAGEPAYLOADTYPE']._serialized_end=326
# @@protoc_insertion_point(module_scope)
