# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: command_request.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'command_request.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x63ommand_request.proto\x12!Aws.IoTFleetWise.Schemas.Commands\"\xb0\x01\n\x0e\x43ommandRequest\x12\x12\n\ncommand_id\x18\x10 \x01(\t\x12\x12\n\ntimeout_ms\x18\x11 \x01(\x04\x12N\n\x10\x61\x63tuator_command\x18\x12 \x01(\x0b\x32\x32.Aws.IoTFleetWise.Schemas.Commands.ActuatorCommandH\x00\x12\x1b\n\x13issued_timestamp_ms\x18\x14 \x01(\x04\x42\t\n\x07\x43ommand\"\xb5\x01\n\x0f\x41\x63tuatorCommand\x12\x11\n\tsignal_id\x18\x01 \x01(\r\x12 \n\x18\x64\x65\x63oder_manifest_sync_id\x18\x02 \x01(\t\x12\x16\n\x0c\x64ouble_value\x18\x03 \x01(\x01H\x00\x12\x17\n\rboolean_value\x18\x04 \x01(\x08H\x00\x12\x15\n\x0bint32_value\x18\t \x01(\x11H\x00\x12\x16\n\x0cstring_value\x18\x0e \x01(\tH\x00\x42\r\n\x0bSignalValueB$\n\"com.amazonaws.iot.autobahn.schemasb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'command_request_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\"com.amazonaws.iot.autobahn.schemas'
  _globals['_COMMANDREQUEST']._serialized_start=61
  _globals['_COMMANDREQUEST']._serialized_end=237
  _globals['_ACTUATORCOMMAND']._serialized_start=240
  _globals['_ACTUATORCOMMAND']._serialized_end=421
# @@protoc_insertion_point(module_scope)
