FROM public.ecr.aws/ubuntu/ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 python3-pip iproute2 && \
    rm -rf /var/lib/apt/lists/*
RUN pip3 install --no-cache-dir python-can cantools msgpack paho-mqtt boto3
WORKDIR /app
