# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: autonomic/ext/event/state/bootstrap.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'autonomic/ext/event/state/bootstrap.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)autonomic/ext/event/state/bootstrap.proto\x12#autonomic.ext.event.state.bootstrap*\x9a\x02\n\x17WellKnownBootstrapState\x12\x11\n\rUNKNOWN_STATE\x10\x00\x12\r\n\tREQUESTED\x10\x01\x12\x1e\n\x1aREQUEST_DECRYPTION_FAILURE\x10\x02\x12\x1b\n\x17INVALID_REQUEST_FAILURE\x10\x03\x12\x17\n\x13INVALID_CSR_FAILURE\x10\x04\x12$\n PRESHARED_KEY_VALIDATION_FAILURE\x10\x05\x12\x1a\n\x16UNKNOWN_DEVICE_FAILURE\x10\x06\x12\x1f\n\x1bTRANSIENT_BOOTSTRAP_FAILURE\x10\x07\x12\x17\n\x13\x43\x41NCELLED_BY_DEVICE\x10\t\x12\x0b\n\x07SUCCESS\x10\x08*\xda\x02\n#WellKnownBootstrapTransitionTrigger\x12\x1e\n\x1aUNKNOWN_TRANSITION_TRIGGER\x10\x00\x12\x1e\n\x1a\x42OOTSTRAP_REQUEST_RECEIVED\x10\x01\x12\x1d\n\x19REQUEST_DECRYPTION_FAILED\x10\x02\x12\x1d\n\x19REQUEST_VALIDATION_FAILED\x10\x03\x12\x19\n\x15\x43SR_VALIDATION_FAILED\x10\x04\x12#\n\x1fPRESHARED_KEY_VALIDATION_FAILED\x10\x05\x12\x18\n\x14\x44\x45VICE_LOOKUP_FAILED\x10\x06\x12\x1b\n\x17INTERNAL_ERROR_OCCURRED\x10\x07\x12 \n\x1cSIGNED_CERTIFICATE_GENERATED\x10\x08\x12\x1c\n\x18\x44\x45VICE_DEADLINE_EXCEEDED\x10\tB\xa4\x01\n\'com.autonomic.ext.event.state.bootstrapB\x1cWellKnownBootstrapStateProtoP\x01ZPgithub.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/event/state\xf8\x01\x01\xa2\x02\x03\x41UTb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'autonomic.ext.event.state.bootstrap_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\'com.autonomic.ext.event.state.bootstrapB\034WellKnownBootstrapStateProtoP\001ZPgithub.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/event/state\370\001\001\242\002\003AUT'
  _globals['_WELLKNOWNBOOTSTRAPSTATE']._serialized_start=83
  _globals['_WELLKNOWNBOOTSTRAPSTATE']._serialized_end=365
  _globals['_WELLKNOWNBOOTSTRAPTRANSITIONTRIGGER']._serialized_start=368
  _globals['_WELLKNOWNBOOTSTRAPTRANSITIONTRIGGER']._serialized_end=714
# @@protoc_insertion_point(module_scope)
