# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: autonomic/ext/provisioning/vehicle_provisioning_exceeded_oem_timeout_event.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'autonomic/ext/provisioning/vehicle_provisioning_exceeded_oem_timeout_event.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from autonomic.ext.provisioning import vehicle_provisioning_result_pb2 as autonomic_dot_ext_dot_provisioning_dot_vehicle__provisioning__result__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nPautonomic/ext/provisioning/vehicle_provisioning_exceeded_oem_timeout_event.proto\x12\x1a\x61utonomic.ext.provisioning\x1a\x1fgoogle/protobuf/timestamp.proto\x1a<autonomic/ext/provisioning/vehicle_provisioning_result.proto\"\xd2\x02\n*VehicleProvisioningExceededOemTimeoutEvent\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03vin\x18\x02 \x01(\t\x12\x42\n\x1eprovisioning_started_timestamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x33\n\x0f\x65vent_timestamp\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12W\n\x19latest_provisioning_event\x18\x05 \x01(\x0b\x32\x34.autonomic.ext.provisioning.VehicleProvisioningEvent\x12$\n\x1cprovisioning_workflow_run_id\x18\x06 \x01(\t\x12\x13\n\x0bregion_code\x18\x07 \x01(\tB\xaf\x01\n\x1e\x63om.autonomic.ext.provisioningB/VehicleProvisioningExceededOemTimeoutEventProtoP\x01ZQgithub.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/provisioning\xf8\x01\x01\xa2\x02\x03\x41UTb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'autonomic.ext.provisioning.vehicle_provisioning_exceeded_oem_timeout_event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\036com.autonomic.ext.provisioningB/VehicleProvisioningExceededOemTimeoutEventProtoP\001ZQgithub.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/provisioning\370\001\001\242\002\003AUT'
  _globals['_VEHICLEPROVISIONINGEXCEEDEDOEMTIMEOUTEVENT']._serialized_start=208
  _globals['_VEHICLEPROVISIONINGEXCEEDEDOEMTIMEOUTEVENT']._serialized_end=546
# @@protoc_insertion_point(module_scope)
