# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: autonomic/ext/command/custom/custom.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'autonomic/ext/command/custom/custom.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)autonomic/ext/command/custom/custom.proto\x12\x1c\x61utonomic.ext.command.custom\x1a\x19google/protobuf/any.proto\"\xc3\x01\n\rCustomRequest\x12j\n\x1b\x63ommand_definition_metadata\x18\x01 \x01(\x0b\x32\x45.autonomic.ext.command.custom.CustomRequest.CommandDefinitionMetadata\x1a\x46\n\x19\x43ommandDefinitionMetadata\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\tB\x8f\x01\n com.autonomic.ext.command.customB\x0b\x43ustomProtoP\x01ZSgithub.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/command/custom\xf8\x01\x01\xa2\x02\x03\x41UTb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'autonomic.ext.command.custom.custom_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n com.autonomic.ext.command.customB\013CustomProtoP\001ZSgithub.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/command/custom\370\001\001\242\002\003AUT'
  _globals['_CUSTOMREQUEST']._serialized_start=103
  _globals['_CUSTOMREQUEST']._serialized_end=298
  _globals['_CUSTOMREQUEST_COMMANDDEFINITIONMETADATA']._serialized_start=228
  _globals['_CUSTOMREQUEST_COMMANDDEFINITIONMETADATA']._serialized_end=298
# @@protoc_insertion_point(module_scope)
