FROM public.ecr.aws/lambda/python:3.11

COPY requirements.txt .
RUN pip install -r requirements.txt -t /asset

COPY lambda_handler_grpc.py /asset/
COPY grpc_lambda_handler.py /asset/
COPY msk_writer.py /asset/
COPY consumers/ /asset/consumers/
COPY ford/ /asset/ford/
COPY autonomic/ /asset/autonomic/
COPY google/ /asset/google/

WORKDIR /asset
CMD ["bash"]
