# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: autonomic/ext/telemetry/enumerations/battery_status.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'autonomic/ext/telemetry/enumerations/battery_status.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n9autonomic/ext/telemetry/enumerations/battery_status.proto\x12\x32\x61utonomic.ext.telemetry.enumerations.batteryStatus*k\n\rBatteryStatus\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0e\n\nSUFFICIENT\x10\x01\x12\x0f\n\x0bLOW_VOLTAGE\x10\x02\x12\x0b\n\x07WARNING\x10\x03\x12\x0e\n\nDISCHARGED\x10\x04\x12\x0f\n\x0bUNAVAILABLE\x10\x05\x42\xa6\x01\n(com.autonomic.ext.telemetry.enumerationsB\x12\x42\x61tteryStatusProtoP\x01Z[github.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/telemetry/enumerations\xf8\x01\x01\xa2\x02\x03\x41UTb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'autonomic.ext.telemetry.enumerations.battery_status_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n(com.autonomic.ext.telemetry.enumerationsB\022BatteryStatusProtoP\001Z[github.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/telemetry/enumerations\370\001\001\242\002\003AUT'
  _globals['_BATTERYSTATUS']._serialized_start=113
  _globals['_BATTERYSTATUS']._serialized_end=220
# @@protoc_insertion_point(module_scope)
