# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: autonomic/ext/telemetry/enumerations/diesel_exhaust_filter_automatic_clean_status.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'autonomic/ext/telemetry/enumerations/diesel_exhaust_filter_automatic_clean_status.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nWautonomic/ext/telemetry/enumerations/diesel_exhaust_filter_automatic_clean_status.proto\x12Lautonomic.ext.telemetry.enumerations.dieselExhaustFilterAutomaticCleanStatus*T\n\'DieselExhaustFilterAutomaticCleanStatus\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0f\n\x0bNOT_ALLOWED\x10\x01\x12\x0b\n\x07\x41LLOWED\x10\x02\x42\xc3\x01\n(com.autonomic.ext.telemetry.enumerationsB,DieselExhaustFilterAutomaticCleanStatusProtoP\x01Z[github.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/telemetry/enumerations\xb8\x01\x01\xf8\x01\x01\xa2\x02\x03\x41UTb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'autonomic.ext.telemetry.enumerations.diesel_exhaust_filter_automatic_clean_status_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n(com.autonomic.ext.telemetry.enumerationsB,DieselExhaustFilterAutomaticCleanStatusProtoP\001Z[github.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/telemetry/enumerations\270\001\001\370\001\001\242\002\003AUT'
  _globals['_DIESELEXHAUSTFILTERAUTOMATICCLEANSTATUS']._serialized_start=169
  _globals['_DIESELEXHAUSTFILTERAUTOMATICCLEANSTATUS']._serialized_end=253
# @@protoc_insertion_point(module_scope)
