# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: autonomic/ext/telemetry/enumerations/mitigation_brake_status.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'autonomic/ext/telemetry/enumerations/mitigation_brake_status.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nBautonomic/ext/telemetry/enumerations/mitigation_brake_status.proto\x12:autonomic.ext.telemetry.enumerations.mitigationBrakeStatus*i\n\x15MitigationBrakeStatus\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x19\n\x15\x42RAKE_NOT_PRE_CHARGED\x10\x01\x12\x15\n\x11\x42RAKE_PRE_CHARGED\x10\x02\x12\x11\n\rBRAKE_APPLIED\x10\x03\x42\xae\x01\n(com.autonomic.ext.telemetry.enumerationsB\x1aMitigationBrakeStatusProtoP\x01Z[github.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/telemetry/enumerations\xf8\x01\x01\xa2\x02\x03\x41UTb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'autonomic.ext.telemetry.enumerations.mitigation_brake_status_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n(com.autonomic.ext.telemetry.enumerationsB\032MitigationBrakeStatusProtoP\001Z[github.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/telemetry/enumerations\370\001\001\242\002\003AUT'
  _globals['_MITIGATIONBRAKESTATUS']._serialized_start=130
  _globals['_MITIGATIONBRAKESTATUS']._serialized_end=235
# @@protoc_insertion_point(module_scope)
