# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: autonomic/ext/telemetry/enumerations/trailer_light_check_status.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'autonomic/ext/telemetry/enumerations/trailer_light_check_status.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nEautonomic/ext/telemetry/enumerations/trailer_light_check_status.proto\x12<autonomic.ext.telemetry.enumerations.trailerLightCheckStatus*R\n\x17TrailerLightCheckStatus\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0f\n\x0bIN_PROGRESS\x10\x01\x12\x0b\n\x07STOPPED\x10\x02\x12\x0c\n\x08\x43OMPLETE\x10\x03\x42\xb0\x01\n(com.autonomic.ext.telemetry.enumerationsB\x1cTrailerLightCheckStatusProtoP\x01Z[github.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/telemetry/enumerations\xf8\x01\x01\xa2\x02\x03\x41UTb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'autonomic.ext.telemetry.enumerations.trailer_light_check_status_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n(com.autonomic.ext.telemetry.enumerationsB\034TrailerLightCheckStatusProtoP\001Z[github.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/telemetry/enumerations\370\001\001\242\002\003AUT'
  _globals['_TRAILERLIGHTCHECKSTATUS']._serialized_start=135
  _globals['_TRAILERLIGHTCHECKSTATUS']._serialized_end=217
# @@protoc_insertion_point(module_scope)
