# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: autonomic/ext/command/profile/change_config_profile.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'autonomic/ext/command/profile/change_config_profile.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n9autonomic/ext/command/profile/change_config_profile.proto\x12\x1d\x61utonomic.ext.command.profile\"2\n\x1a\x43hangeConfigProfileRequest\x12\x14\n\x0cprofile_name\x18\x01 \x01(\tB\x9e\x01\n!com.autonomic.ext.command.profileB\x18\x43hangeConfigProfileProtoP\x01ZTgithub.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/command/profile\xf8\x01\x01\xa2\x02\x03\x41UTb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'autonomic.ext.command.profile.change_config_profile_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n!com.autonomic.ext.command.profileB\030ChangeConfigProfileProtoP\001ZTgithub.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/command/profile\370\001\001\242\002\003AUT'
  _globals['_CHANGECONFIGPROFILEREQUEST']._serialized_start=92
  _globals['_CHANGECONFIGPROFILEREQUEST']._serialized_end=142
# @@protoc_insertion_point(module_scope)
