# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: autonomic/ext/common/range.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'autonomic/ext/common/range.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n autonomic/ext/common/range.proto\x12\x1b\x61utonomic.ext.common.entity\"\x8e\x01\n\x05Range\x12:\n\tint_range\x18\x01 \x01(\x0b\x32%.autonomic.ext.common.entity.IntRangeH\x00\x12@\n\x0c\x64ouble_range\x18\x02 \x01(\x0b\x32(.autonomic.ext.common.entity.DoubleRangeH\x00\x42\x07\n\x05value\"4\n\x08IntRange\x12\x13\n\x0blower_bound\x18\x01 \x01(\x03\x12\x13\n\x0bupper_bound\x18\x02 \x01(\x03\"7\n\x0b\x44oubleRange\x12\x13\n\x0blower_bound\x18\x01 \x01(\x01\x12\x13\n\x0bupper_bound\x18\x02 \x01(\x01\x42\x8a\x01\n\x1e\x63om.autonomic.ext.common.rangeB\x10\x43ommonRangeProtoP\x01ZKgithub.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/common\xf8\x01\x01\xa2\x02\x03\x41UTb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'autonomic.ext.common.range_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\036com.autonomic.ext.common.rangeB\020CommonRangeProtoP\001ZKgithub.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/common\370\001\001\242\002\003AUT'
  _globals['_RANGE']._serialized_start=66
  _globals['_RANGE']._serialized_end=208
  _globals['_INTRANGE']._serialized_start=210
  _globals['_INTRANGE']._serialized_end=262
  _globals['_DOUBLERANGE']._serialized_start=264
  _globals['_DOUBLERANGE']._serialized_end=319
# @@protoc_insertion_point(module_scope)
