# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: autonomic/ext/deployment/device_deployment.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'autonomic/ext/deployment/device_deployment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0autonomic/ext/deployment/device_deployment.proto\x12\x18\x61utonomic.ext.deployment\".\n\x11\x41rtifactReference\x12\x0b\n\x03uri\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\"0\n!RegisterDeploymentListenerRequest\x12\x0b\n\x03vin\x18\x01 \x01(\t\"\x91\x01\n\x17\x44\x65viceDeploymentRequest\x12\x16\n\x0e\x63orrelation_id\x18\x01 \x01(\x0c\x12>\n\tartifacts\x18\x02 \x03(\x0b\x32+.autonomic.ext.deployment.ArtifactReference\x12\x1e\n\x12oem_correlation_id\x18\x03 \x01(\x0c\x42\x02\x18\x01\"\x9a\x01\n\x1f\x44\x65viceDeploymentRequestEnvelope\x12O\n\x12\x64\x65ployment_request\x18\x01 \x01(\x0b\x32\x31.autonomic.ext.deployment.DeviceDeploymentRequestH\x00\x12\x1b\n\x11\x65ncrypted_request\x18\x02 \x01(\x0cH\x00\x42\t\n\x07request2\xad\x01\n\x10\x44\x65viceDeployment\x12\x98\x01\n\x1aRegisterDeploymentListener\x12;.autonomic.ext.deployment.RegisterDeploymentListenerRequest\x1a\x39.autonomic.ext.deployment.DeviceDeploymentRequestEnvelope\"\x00\x30\x01\x42\x91\x01\n\x1c\x63om.autonomic.ext.deploymentB\x15\x44\x65viceDeploymentProtoP\x01ZOgithub.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/deployment\xf8\x01\x01\xa2\x02\x03\x41UTb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'autonomic.ext.deployment.device_deployment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\034com.autonomic.ext.deploymentB\025DeviceDeploymentProtoP\001ZOgithub.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/deployment\370\001\001\242\002\003AUT'
  _globals['_DEVICEDEPLOYMENTREQUEST'].fields_by_name['oem_correlation_id']._loaded_options = None
  _globals['_DEVICEDEPLOYMENTREQUEST'].fields_by_name['oem_correlation_id']._serialized_options = b'\030\001'
  _globals['_ARTIFACTREFERENCE']._serialized_start=78
  _globals['_ARTIFACTREFERENCE']._serialized_end=124
  _globals['_REGISTERDEPLOYMENTLISTENERREQUEST']._serialized_start=126
  _globals['_REGISTERDEPLOYMENTLISTENERREQUEST']._serialized_end=174
  _globals['_DEVICEDEPLOYMENTREQUEST']._serialized_start=177
  _globals['_DEVICEDEPLOYMENTREQUEST']._serialized_end=322
  _globals['_DEVICEDEPLOYMENTREQUESTENVELOPE']._serialized_start=325
  _globals['_DEVICEDEPLOYMENTREQUESTENVELOPE']._serialized_end=479
  _globals['_DEVICEDEPLOYMENT']._serialized_start=482
  _globals['_DEVICEDEPLOYMENT']._serialized_end=655
# @@protoc_insertion_point(module_scope)
