/*-
 * ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
 * Autonomic Proprietary 1.0
 * ——————————————————————————————————————————————————————————————————————————————
 * Copyright (C) 2017 - 2019 Autonomic, LLC - All rights reserved
 * ——————————————————————————————————————————————————————————————————————————————
 * Proprietary and confidential.
 *
 * NOTICE:  All information contained herein is, and remains the property of
 * Autonomic, LLC and its suppliers, if any.  The intellectual and technical
 * concepts contained herein are proprietary to Autonomic, LLC and its suppliers
 * and may be covered by U.S. and Foreign Patents, patents in process, and are
 * protected by trade secret or copyright law. Dissemination of this information
 * or reproduction of this material is strictly forbidden unless prior written
 * permission is obtained from Autonomic, LLC.
 *
 * Unauthorized copy of this file, via any medium is strictly prohibited.
 * ______________________________________________________________________________
 */
syntax = "proto3";

package autonomic.ext.provisioning;

option go_package = "github.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/provisioning";
option java_package = "com.autonomic.ext.provisioning";
option java_outer_classname = "VehicleProvisioningExceededOemTimeoutEventProto";
option java_multiple_files = true;
option cc_enable_arenas = true;
option objc_class_prefix = "AUT";

import "google/protobuf/timestamp.proto";
import "autonomic/ext/provisioning/vehicle_provisioning_result.proto";

//The result from the provisioning of a vehicle on the TMC platform.
message VehicleProvisioningExceededOemTimeoutEvent {

  // REQUIRED: Unique identifier for the event - e.g. aui:event:provisioning:vehicle_provisioning_exceeded_oem_timeout_event:<uuid>
  string id = 1;

  // REQUIRED: The VIN of the vehicle associated with the VehicleProvisioningResult
  string vin = 2;

  // REQUIRED: The timestamp at which the vehicle provisioning started
  google.protobuf.Timestamp provisioning_started_timestamp = 3;

  // REQUIRED: The timestamp at which this result was generated
  google.protobuf.Timestamp event_timestamp = 4;

  // REQUIRED: The latest VehicleProvisioningEvent in the provisioning flow
  VehicleProvisioningEvent latest_provisioning_event = 5;

  // REQUIRED: UUID string unique to every provisioning process on TMC
  string provisioning_workflow_run_id = 6;

  // REQUIRED: The region code associated with the primary device connecting to TMC
  string region_code = 7;
}
