// Design Options View — 3 design recommendations the agent generated.
// Engineer reviews tradeoffs (impact / cost / lead time / evidence) and accepts one.
// Acceptance navigates to /digital-thread with the selected option's writeback payload.

import React, { useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import {
  Alert,
  Badge,
  Box,
  Button,
  Cards,
  ColumnLayout,
  Container,
  ExpandableSection,
  Header,
  KeyValuePairs,
  SpaceBetween,
  StatusIndicator,
} from '@cloudscape-design/components';
import {
  DESIGN_OPTIONS,
  type DesignOption,
  HERO_ANOMALY_ID,
  getAnomaly,
} from '../../mock-data-provider/engineering';
import { UI_ROUTES } from '../../utils/constants';

const DesignOptionsView: React.FC = () => {
  const navigate = useNavigate();
  const { caseId } = useParams<{ caseId?: string }>();
  const anomalyId = caseId || HERO_ANOMALY_ID;
  const anomaly = getAnomaly(anomalyId);
  const [selectedOptionId, setSelectedOptionId] = useState<string | null>(null);

  const handleAccept = (optionId: string) => {
    setSelectedOptionId(optionId);
    setTimeout(() => {
      navigate(`${UI_ROUTES.DIGITAL_THREAD}?option=${optionId}&from=${anomalyId}`);
    }, 800);
  };

  if (!anomaly) {
    return <Alert type="error">Anomaly {anomalyId} not found.</Alert>;
  }

  return (
    <SpaceBetween size="l">
      {/* Header context — page title + description rendered globally via PageHeader.
          Inline body keeps the agent context narrative without duplicating the title. */}
      <Container>
        <SpaceBetween size="xs">
          <SpaceBetween direction="horizontal" size="xs" alignItems="center">
            <Badge color="blue">3 options · 1 recommended</Badge>
            <Box variant="small" color="text-body-secondary">
              Generated by Product Engineering Agent for {anomaly.title}
            </Box>
          </SpaceBetween>
          <Box variant="p">
            The agent explored three design vectors in parallel: cooling architecture, thermal mass, and supplier
            strategy. Each option projects SoH improvement, BOM cost delta, and qualification lead time against the
            BE.07 launch window. Engineer review required to advance any option to the digital thread.
          </Box>
          <Box variant="small" color="text-body-secondary">
            <strong>5 options/week → 5,000 options overnight:</strong> the agent surfaces 3 here for engineer review;
            the same exploration pattern can be scaled to ranked design-space sweeps overnight against engineering
            criteria.
          </Box>
        </SpaceBetween>
      </Container>

      {/* Options cards */}
      <Cards
        cardDefinition={{
          header: (item: DesignOption) => (
            <SpaceBetween direction="horizontal" size="xs" alignItems="center">
              <Box variant="h3">{item.shortLabel}</Box>
              {item.recommended && (
                <StatusIndicator type="success">Agent-recommended</StatusIndicator>
              )}
            </SpaceBetween>
          ),
          sections: [
            {
              id: 'description',
              content: (item: DesignOption) => (
                <SpaceBetween size="xs">
                  <Box variant="p" fontWeight="bold">
                    {item.title}
                  </Box>
                  <Box variant="p">{item.description}</Box>
                </SpaceBetween>
              ),
            },
            {
              id: 'impact',
              header: 'Projected impact',
              content: (item: DesignOption) => (
                <ColumnLayout columns={3} variant="text-grid">
                  <KeyValuePairs
                    columns={1}
                    items={[
                      {
                        label: 'SoH degradation',
                        value: (
                          <Box color="text-status-success" fontWeight="bold">
                            {item.projectedImpact.soHDegradationDelta_pct.toFixed(1)}%
                          </Box>
                        ),
                      },
                    ]}
                  />
                  <KeyValuePairs
                    columns={1}
                    items={[
                      {
                        label: 'Thermal margin gain',
                        value: (
                          <Box fontWeight="bold">
                            +{item.projectedImpact.thermalMarginGain_C.toFixed(1)}°C
                          </Box>
                        ),
                      },
                    ]}
                  />
                  <KeyValuePairs
                    columns={1}
                    items={[
                      {
                        label: 'Range impact',
                        value: (
                          <Box>
                            {item.projectedImpact.rangeImpact_pct >= 0 ? '+' : ''}
                            {item.projectedImpact.rangeImpact_pct.toFixed(1)}%
                          </Box>
                        ),
                      },
                    ]}
                  />
                </ColumnLayout>
              ),
            },
            {
              id: 'cost',
              header: 'Cost & qualification',
              content: (item: DesignOption) => (
                <ColumnLayout columns={2} variant="text-grid">
                  <KeyValuePairs
                    columns={1}
                    items={[
                      {
                        label: 'BOM cost delta',
                        value: (
                          <Box fontWeight="bold">
                            +${item.costDelta_perVehicle_USD}/vehicle
                          </Box>
                        ),
                      },
                    ]}
                  />
                  <KeyValuePairs
                    columns={1}
                    items={[
                      {
                        label: 'Qualification lead time',
                        value: (
                          <Box fontWeight="bold">
                            {item.qualificationLeadTime_weeks} weeks
                          </Box>
                        ),
                      },
                    ]}
                  />
                </ColumnLayout>
              ),
            },
            {
              id: 'rationale',
              content: (item: DesignOption) => (
                <ExpandableSection headerText="Rationale & evidence" variant="footer">
                  <SpaceBetween size="xs">
                    <Box variant="p">{item.rationale}</Box>
                    <Box variant="small" color="text-body-secondary">
                      Evidence: {item.evidenceDocIds.join(' · ')}
                    </Box>
                  </SpaceBetween>
                </ExpandableSection>
              ),
            },
            {
              id: 'thread',
              content: (item: DesignOption) => (
                <ExpandableSection
                  headerText={`Digital Thread writeback (${item.digitalThreadActions.length} actions)`}
                  variant="footer"
                >
                  <SpaceBetween size="s">
                    {item.digitalThreadActions.map((action, idx) => (
                      <Box key={idx}>
                        <Box>
                          <Badge color="grey">{action.type}</Badge>{' '}
                          <Box display="inline" fontWeight="bold">
                            {action.target}
                          </Box>
                        </Box>
                        <Box variant="small" color="text-body-secondary" margin={{ left: 's' }}>
                          {action.description}
                        </Box>
                      </Box>
                    ))}
                  </SpaceBetween>
                </ExpandableSection>
              ),
            },
            {
              id: 'action',
              content: (item: DesignOption) => (
                <Box margin={{ top: 's' }}>
                  <Button
                    variant={item.recommended ? 'primary' : 'normal'}
                    iconName="external"
                    iconAlign="right"
                    onClick={() => handleAccept(item.optionId)}
                    loading={selectedOptionId === item.optionId}
                  >
                    Accept option & push to Digital Thread
                  </Button>
                </Box>
              ),
            },
          ],
        }}
        cardsPerRow={[{ cards: 1 }]}
        items={DESIGN_OPTIONS}
        loadingText="Loading options"
        empty={<Box>No options available.</Box>}
        header={null}
      />

      {selectedOptionId && (
        <Alert type="success" header="Pushing to Digital Thread…">
          Routing requirement update, simulation parameters, and design review ticket to engineering systems.
        </Alert>
      )}
    </SpaceBetween>
  );
};

export default DesignOptionsView;
