# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: autonomic/ext/event/state/well_known_command_states.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'autonomic/ext/event/state/well_known_command_states.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n9autonomic/ext/event/state/well_known_command_states.proto\x12\'autonomic.ext.event.state.commandstates*\x93\x01\n\"WellKnownCommandFiniteStateMachine\x12\x17\n\x13UNKNOWN_COMMAND_FSM\x10\x00\x12\x19\n\x15\x43OMMAND_WITH_RESPONSE\x10\x01\x12\x1c\n\x18\x43OMMAND_WITHOUT_RESPONSE\x10\x02\x12\x1b\n\x17\x43OMMAND_WITH_USER_INPUT\x10\x03*\x97\x05\n\x15WellKnownCommandState\x12\x11\n\rUNKNOWN_STATE\x10\x00\x12\r\n\tREQUESTED\x10\x01\x12\x1c\n\x18\x44\x45LIVERY_FROM_TMC_QUEUED\x10\x02\x12\"\n\x1eOEM_CLOUD_DELIVERY_IN_PROGRESS\x10\n\x12$\n OEM_CLOUD_PROCESSING_IN_PROGRESS\x10\x14\x12\"\n\x1e\x44\x45LIVERY_FROM_OEM_CLOUD_QUEUED\x10\x15\x12\x1f\n\x1b\x44\x45VICE_DELIVERY_IN_PROGRESS\x10\x1e\x12\x16\n\x12RECEIVED_BY_DEVICE\x10 \x12\x0b\n\x07\x45XPIRED\x10\x32\x12\r\n\tCANCELLED\x10\x33\x12&\n\"RETRIABLE_COMMAND_DELIVERY_FAILURE\x10\x34\x12\x1c\n\x18\x43OMMAND_DELIVERY_FAILURE\x10\x35\x12&\n\"DEVICE_RESPONSE_PROCESSING_FAILURE\x10\x36\x12)\n%DEVICE_COMMAND_VALIDATION_IN_PROGRESS\x10\x64\x12%\n!DEVICE_COMMAND_VALIDATION_FAILURE\x10\x65\x12!\n\x1d\x43OMMAND_IN_PROGRESS_ON_DEVICE\x10\x66\x12 \n\x1c\x44\x45VICE_WAITING_ON_USER_INPUT\x10g\x12\x1f\n\x1b\x43OMMAND_SUCCEEDED_ON_DEVICE\x10h\x12\x1c\n\x18\x43OMMAND_FAILED_ON_DEVICE\x10i\x12\x1e\n\x1a\x43OMMAND_FINISHED_ON_DEVICE\x10j\x12\x17\n\x13RECEIVED_USER_INPUT\x10kB\xa7\x01\n+com.autonomic.ext.event.state.commandstatesB\x1bWellKnownCommandStatesProtoP\x01ZPgithub.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/event/state\xf8\x01\x01\xa2\x02\x03\x41UTb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'autonomic.ext.event.state.well_known_command_states_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n+com.autonomic.ext.event.state.commandstatesB\033WellKnownCommandStatesProtoP\001ZPgithub.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/event/state\370\001\001\242\002\003AUT'
  _globals['_WELLKNOWNCOMMANDFINITESTATEMACHINE']._serialized_start=103
  _globals['_WELLKNOWNCOMMANDFINITESTATEMACHINE']._serialized_end=250
  _globals['_WELLKNOWNCOMMANDSTATE']._serialized_start=253
  _globals['_WELLKNOWNCOMMANDSTATE']._serialized_end=916
# @@protoc_insertion_point(module_scope)
