# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: autonomic/ext/asset/enumerations/vehicle_lifecycle_status.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'autonomic/ext/asset/enumerations/vehicle_lifecycle_status.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n?autonomic/ext/asset/enumerations/vehicle_lifecycle_status.proto\x12\x37\x61utonomic.ext.asset.enumerations.vehicleLifecycleStatus*K\n\x16VehicleLifecycleStatus\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x10\n\x0cPRE_DELIVERY\x10\x64\x12\x12\n\rPOST_DELIVERY\x10\xc8\x01\x42\xa7\x01\n$com.autonomic.ext.asset.enumerationsB\x1bVehicleLifecycleStatusProtoP\x01ZWgithub.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/asset/enumerations\xf8\x01\x01\xa2\x02\x03\x41UTb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'autonomic.ext.asset.enumerations.vehicle_lifecycle_status_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n$com.autonomic.ext.asset.enumerationsB\033VehicleLifecycleStatusProtoP\001ZWgithub.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/asset/enumerations\370\001\001\242\002\003AUT'
  _globals['_VEHICLELIFECYCLESTATUS']._serialized_start=124
  _globals['_VEHICLELIFECYCLESTATUS']._serialized_end=199
# @@protoc_insertion_point(module_scope)
