# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: autonomic/ext/validation/validation_options.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'autonomic/ext/validation/validation_options.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1autonomic/ext/validation/validation_options.proto\x12\x18\x61utonomic.ext.validation*@\n\x12TimestampBoundType\x12\x0c\n\x08NO_BOUND\x10\x00\x12\x0c\n\x08\x43REATION\x10\x01\x12\x0e\n\nEXPIRATION\x10\x02\x42\x92\x01\n\x1c\x63om.autonomic.ext.validationB\x16ValidationOptionsProtoP\x01ZOgithub.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/validation\xf8\x01\x01\xa2\x02\x03\x41UTb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'autonomic.ext.validation.validation_options_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\034com.autonomic.ext.validationB\026ValidationOptionsProtoP\001ZOgithub.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/validation\370\001\001\242\002\003AUT'
  _globals['_TIMESTAMPBOUNDTYPE']._serialized_start=79
  _globals['_TIMESTAMPBOUNDTYPE']._serialized_end=143
# @@protoc_insertion_point(module_scope)
