# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: autonomic/ext/telemetry/ingest_audit.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'autonomic/ext/telemetry/ingest_audit.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*autonomic/ext/telemetry/ingest_audit.proto\x12\x17\x61utonomic.ext.telemetry\x1a\x1fgoogle/protobuf/timestamp.proto\"-\n\x04Rule\x12\x0f\n\x07rule_id\x18\x01 \x01(\x05\x12\x14\n\x0crule_version\x18\x02 \x01(\x05\"l\n\x0bIngestAudit\x12\x15\n\rdenied_fields\x18\x01 \x03(\t\x12\x18\n\x10permitted_fields\x18\x02 \x03(\t\x12,\n\x05rules\x18\x03 \x03(\x0b\x32\x1d.autonomic.ext.telemetry.RuleB\x8a\x01\n\x1b\x63om.autonomic.ext.telemetryB\x10IngestAuditProtoP\x01ZNgithub.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/telemetry\xf8\x01\x01\xa2\x02\x03\x41UTb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'autonomic.ext.telemetry.ingest_audit_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.autonomic.ext.telemetryB\020IngestAuditProtoP\001ZNgithub.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/telemetry\370\001\001\242\002\003AUT'
  _globals['_RULE']._serialized_start=104
  _globals['_RULE']._serialized_end=149
  _globals['_INGESTAUDIT']._serialized_start=151
  _globals['_INGESTAUDIT']._serialized_end=259
# @@protoc_insertion_point(module_scope)
