# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: autonomic/ext/telemetry/report_tag.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'autonomic/ext/telemetry/report_tag.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(autonomic/ext/telemetry/report_tag.proto\x12\x17\x61utonomic.ext.telemetry\"Z\n\x0cReportTagKey\x12J\n\x15well_known_report_tag\x18\x01 \x01(\x0e\x32+.autonomic.ext.telemetry.WellKnownReportTag\"^\n\x0eReportTagValue\x12L\n\x16well_known_report_type\x18\x01 \x01(\x0e\x32,.autonomic.ext.telemetry.WellKnownReportType\"\x7f\n\tReportTag\x12\x36\n\x07tag_key\x18\x01 \x01(\x0b\x32%.autonomic.ext.telemetry.ReportTagKey\x12:\n\ttag_value\x18\x02 \x01(\x0b\x32\'.autonomic.ext.telemetry.ReportTagValue*p\n\x13WellKnownReportType\x12\x17\n\x13UNKNOWN_REPORT_TYPE\x10\x00\x12\x0e\n\nANTI_THEFT\x10\x01\x12\x12\n\x0eVEHICLE_HEALTH\x10\x02\x12\x08\n\x04MIER\x10\x03\x12\x12\n\x0eVEHICLE_STATUS\x10\x04*=\n\x12WellKnownReportTag\x12\x16\n\x12UNKNOWN_REPORT_TAG\x10\x00\x12\x0f\n\x0bREPORT_TYPE\x10\x01\x42\x88\x01\n\x1b\x63om.autonomic.ext.telemetryB\x0eReportTagProtoP\x01ZNgithub.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/telemetry\xf8\x01\x01\xa2\x02\x03\x41UTb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'autonomic.ext.telemetry.report_tag_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.autonomic.ext.telemetryB\016ReportTagProtoP\001ZNgithub.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/telemetry\370\001\001\242\002\003AUT'
  _globals['_WELLKNOWNREPORTTYPE']._serialized_start=386
  _globals['_WELLKNOWNREPORTTYPE']._serialized_end=498
  _globals['_WELLKNOWNREPORTTAG']._serialized_start=500
  _globals['_WELLKNOWNREPORTTAG']._serialized_end=561
  _globals['_REPORTTAGKEY']._serialized_start=69
  _globals['_REPORTTAGKEY']._serialized_end=159
  _globals['_REPORTTAGVALUE']._serialized_start=161
  _globals['_REPORTTAGVALUE']._serialized_end=255
  _globals['_REPORTTAG']._serialized_start=257
  _globals['_REPORTTAG']._serialized_end=384
# @@protoc_insertion_point(module_scope)
