# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: autonomic/ext/command/antitheft/anti_theft.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'autonomic/ext/command/antitheft/anti_theft.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0autonomic/ext/command/antitheft/anti_theft.proto\x12\x1f\x61utonomic.ext.command.antitheft\"\xbe\x06\n\x10\x41ntiTheftRequest\x12g\n\x17\x61nti_theft_request_type\x18\x01 \x01(\x0e\x32\x46.autonomic.ext.command.antitheft.AntiTheftRequest.AntiTheftRequestType\x12\x19\n\x11\x66requency_seconds\x18\x03 \x01(\x05\x12v\n\x1dvehicle_inhibition_properties\x18\x04 \x01(\x0b\x32M.autonomic.ext.command.antitheft.AntiTheftRequest.VehicleInhibitionPropertiesH\x00\x1a\x8f\x02\n\x1bVehicleInhibitionProperties\x12\x98\x01\n\"anti_theft_vehicle_inhibition_type\x18\x01 \x01(\x0e\x32l.autonomic.ext.command.antitheft.AntiTheftRequest.VehicleInhibitionProperties.AntiTheftVehicleInhibitionType\"U\n\x1e\x41ntiTheftVehicleInhibitionType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x11\n\rINHIBIT_CRANK\x10\x01\x12\x13\n\x0fINHIBIT_DRIVING\x10\x02\"\xfc\x01\n\x14\x41ntiTheftRequestType\x12#\n\x1fUNKNOWN_ANTI_THEFT_REQUEST_TYPE\x10\x00\x12&\n\"DISABLE_EARLY_ANTI_THEFT_REPORTING\x10\x02\x12\x1a\n\x16\x45NABLE_ANTI_THEFT_MODE\x10\x03\x12\x1b\n\x17\x44ISABLE_ANTI_THEFT_MODE\x10\x04\x12\x1b\n\x17REPORT_CURRENT_LOCATION\x10\x05\x12\x1c\n\x18\x41PPLY_VEHICLE_INHIBITION\x10\x06\x12\x1d\n\x19REMOVE_VEHICLE_INHIBITION\x10\x07\"\x04\x08\x01\x10\x01\x42\x17\n\x15\x61nti_theft_propertiesJ\x04\x08\x02\x10\x03\x42\x98\x01\n#com.autonomic.ext.command.antitheftB\x0e\x41ntiTheftProtoP\x01ZVgithub.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/command/antitheft\xf8\x01\x01\xa2\x02\x03\x41UTb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'autonomic.ext.command.antitheft.anti_theft_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n#com.autonomic.ext.command.antitheftB\016AntiTheftProtoP\001ZVgithub.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/command/antitheft\370\001\001\242\002\003AUT'
  _globals['_ANTITHEFTREQUEST']._serialized_start=86
  _globals['_ANTITHEFTREQUEST']._serialized_end=916
  _globals['_ANTITHEFTREQUEST_VEHICLEINHIBITIONPROPERTIES']._serialized_start=359
  _globals['_ANTITHEFTREQUEST_VEHICLEINHIBITIONPROPERTIES']._serialized_end=630
  _globals['_ANTITHEFTREQUEST_VEHICLEINHIBITIONPROPERTIES_ANTITHEFTVEHICLEINHIBITIONTYPE']._serialized_start=545
  _globals['_ANTITHEFTREQUEST_VEHICLEINHIBITIONPROPERTIES_ANTITHEFTVEHICLEINHIBITIONTYPE']._serialized_end=630
  _globals['_ANTITHEFTREQUEST_ANTITHEFTREQUESTTYPE']._serialized_start=633
  _globals['_ANTITHEFTREQUEST_ANTITHEFTREQUESTTYPE']._serialized_end=885
# @@protoc_insertion_point(module_scope)
