// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

/**
 * Verdict-driven UX regression suite — 6 renderers x 3 verdicts = 18 cases.
 *
 * Spec: .kiro/specs/2026-09-10-cms-sovd-routine-result-contracts/ Group 6 T6.1
 *   D5 — the server-computed verdict is authoritative. The UI must never
 *        recompute it, and thresholds must never be restated in TypeScript.
 *
 * WHERE THE TRUTH COMES FROM
 * --------------------------
 * Every payload and every expected verdict in this suite is read from
 * `verdict-fixtures.generated.json`, generated by
 * `services/_shared/export_verdict_fixtures.py` by running each payload
 * through the schema's own `verdict_from_result`. This file contains no
 * thresholds, no payload/verdict pairings of its own, and no copy of the
 * verdict labels.
 *
 * That matters because the obvious way to write this suite is the broken one:
 * hardcode `{ leak_rate_ccm: 2.0 }` and expect `out_of_spec`. Move the Python
 * threshold to 3.0 and that test stays green while asserting a pairing that is
 * now false — exactly the bug D5 forbids.
 *
 * Likewise, the expected banner label and StatusIndicator type come from the
 * fixture's `verdict_presentation` block, NOT from `../types`. If this suite
 * imported the expected label from the same constant the component renders, it
 * would assert only that the component agrees with itself, and a mutation to
 * `types.ts` would change both sides and still pass.
 * `test_types_ts_agrees_with_the_generated_contract` compares the two copies
 * explicitly instead.
 *
 * If this suite fails after a Python change, regenerate:
 *   cd services && python3 -m _shared.export_verdict_fixtures --write
 */

import React from 'react';
import { render, screen } from '@testing-library/react';
import { describe, it, expect } from 'vitest';

import fixtureData from './verdict-fixtures.generated.json';
import { rendererFor } from '../index';
import { VERDICT_LABEL, verdictType } from '../types';
import type { Verdict } from '../types';

// ── Fixture shape (the JSON is generated; these mirror its contract) ─────────

interface VerdictFixture {
  routine_id: string;
  verdict: string;
  verdict_source: 'python' | 'presentation_only';
  result: Record<string, unknown>;
  renderer_hint: string;
  schema_version: number;
}

interface VerdictPresentation {
  label: string;
  indicator_type: string;
}

const FIXTURES = fixtureData.fixtures as unknown as readonly VerdictFixture[];
const PRESENTATION = fixtureData.verdict_presentation as unknown as Record<
  string,
  VerdictPresentation
>;

/**
 * Root `data-testid` per routine renderer.
 *
 * Deliberately an explicit map rather than a derived
 * `routine_id.replace(/_/g, '-') + '-renderer'`: five of the six follow that
 * rule but `pack_isolation_test` renders `pack-isolation-renderer` (no
 * `-test`). A derivation would silently mis-resolve that one, and the test
 * would then fail for the wrong reason.
 */
const RENDERER_TESTID: Record<string, string> = {
  lamp_self_check: 'lamp-self-check-renderer',
  o2_heater_check: 'o2-heater-check-renderer',
  evap_leak_test: 'evap-leak-test-renderer',
  abs_pump_cycle: 'abs-pump-cycle-renderer',
  pack_isolation_test: 'pack-isolation-renderer',
  cell_balance_check: 'cell-balance-check-renderer',
};

const EXPECTED_CASE_COUNT = 18;
const EXPECTED_ROUTINE_COUNT = 6;

// ── Suite-level integrity: an emptied artifact must not silently pass ────────
// `it.each([])` is vacuous in most runners. These assertions run first so a
// truncated or hand-emptied fixture file fails loudly instead of reporting a
// green suite that exercised nothing.

describe('verdict fixture bridge integrity', () => {
  it(`carries exactly ${EXPECTED_CASE_COUNT} fixtures (${EXPECTED_ROUTINE_COUNT} routines x 3 verdicts)`, () => {
    expect(FIXTURES).toHaveLength(EXPECTED_CASE_COUNT);
  });

  it('covers every routine x verdict pair with no duplicates', () => {
    const pairs = FIXTURES.map((f) => `${f.routine_id}:${f.verdict}`);
    expect(new Set(pairs).size).toBe(EXPECTED_CASE_COUNT);

    const routines = new Set(FIXTURES.map((f) => f.routine_id));
    expect(routines.size).toBe(EXPECTED_ROUTINE_COUNT);

    for (const routine of routines) {
      const verdicts = FIXTURES.filter((f) => f.routine_id === routine).map((f) => f.verdict);
      expect(new Set(verdicts)).toEqual(
        new Set(['in_spec', 'marginal', 'out_of_spec']),
      );
    }
  });

  it('has a known renderer testid for every routine in the fixtures', () => {
    for (const routine of new Set(FIXTURES.map((f) => f.routine_id))) {
      expect(RENDERER_TESTID[routine], `no testid mapped for ${routine}`).toBeDefined();
    }
  });

  it('provides a non-empty label and a distinct indicator type per verdict', () => {
    const verdicts = ['in_spec', 'marginal', 'out_of_spec'];
    expect(Object.keys(PRESENTATION).sort()).toEqual([...verdicts].sort());

    for (const v of verdicts) {
      expect(PRESENTATION[v].label.trim().length).toBeGreaterThan(0);
      expect(PRESENTATION[v].indicator_type.trim().length).toBeGreaterThan(0);
    }

    // A fault must not render identically to a clean pass — that is the D5
    // failure mode restated at the presentation layer.
    const types = verdicts.map((v) => PRESENTATION[v].indicator_type);
    expect(new Set(types).size).toBe(types.length);
  });
});

// ── The two-copy comparison that makes the DOM assertions mutation-sensitive ─

describe('types.ts agrees with the generated verdict contract', () => {
  it('VERDICT_LABEL matches the generated labels', () => {
    for (const [verdict, entry] of Object.entries(PRESENTATION)) {
      expect(
        VERDICT_LABEL[verdict as Verdict],
        `types.ts VERDICT_LABEL.${verdict} has drifted from spec D5 / the generated contract`,
      ).toBe(entry.label);
    }
  });

  it('verdictType matches the generated indicator types', () => {
    for (const [verdict, entry] of Object.entries(PRESENTATION)) {
      expect(
        verdictType[verdict as Verdict],
        `types.ts verdictType.${verdict} has drifted from spec D5 / the generated contract`,
      ).toBe(entry.indicator_type);
    }
  });
});

// ── The 18 render cases ─────────────────────────────────────────────────────

describe('routine renderers render the server-computed verdict', () => {
  it.each(
    FIXTURES.map((f) => [`${f.routine_id} / ${f.verdict} (${f.verdict_source})`, f] as const),
  )('%s', (_title, fixture) => {
    const expected = PRESENTATION[fixture.verdict];
    expect(expected, `no presentation entry for verdict ${fixture.verdict}`).toBeDefined();

    const Renderer = rendererFor(fixture.routine_id);
    const { container } = render(
      <Renderer
        response={{
          status: 'SUCCEEDED',
          verdict: fixture.verdict as Verdict,
          result: fixture.result,
        }}
        routineId={fixture.routine_id}
        commandId={`cmd-${fixture.routine_id}-${fixture.verdict}`}
      />,
    );

    // 1. The routine-specific renderer resolved — not a silent RawDrawer
    //    fallback. RawDrawer renders no verdict banner, so a registry
    //    regression would otherwise surface as a confusing banner miss.
    expect(
      screen.getByTestId(RENDERER_TESTID[fixture.routine_id]),
      `${fixture.routine_id} did not render its own renderer — registry fell back?`,
    ).toBeInTheDocument();

    // 2. An element carrying the expected Cloudscape status class also carries
    //    the expected label. Asserting both together is what makes this
    //    sensitive to a verdict->type mutation AND a verdict->label mutation.
    const statusNodes = Array.from(
      container.querySelectorAll(`[class*="status-${expected.indicator_type}"]`),
    );
    expect(
      statusNodes.length,
      `no element with class status-${expected.indicator_type} for verdict ` +
        `${fixture.verdict} — verdictType mapping changed?`,
    ).toBeGreaterThan(0);

    const labelled = statusNodes.some((node) =>
      node.textContent?.includes(expected.label),
    );
    expect(
      labelled,
      `expected an element with class status-${expected.indicator_type} containing ` +
        `"${expected.label}". Found status nodes with text: ` +
        statusNodes.map((n) => JSON.stringify(n.textContent)).join(', '),
    ).toBe(true);
  });
});
