#!/usr/bin/env python3
"""
Seed Event Catalog — populates cms-{stage}-event-catalog DynamoDB table.

Usage:
    python3 seed_event_catalog.py
    AWS_PROFILE=myprofile DEPLOYMENT_STAGE=prod python3 seed_event_catalog.py
"""
import boto3
import os
import time
from decimal import Decimal

PROFILE = os.environ.get('AWS_PROFILE', 'default')
STAGE = os.environ.get('DEPLOYMENT_STAGE', 'dev')
REGION = os.environ.get('AWS_REGION', 'us-east-1')

session = boto3.Session(profile_name=PROFILE, region_name=REGION)
dynamodb = session.resource('dynamodb')
TABLE = f'cms-{STAGE}-event-catalog'

# ── Event Catalog Definitions ──────────────────────────────────────────────
EVENTS = [
    # ── SAFETY events ──────────────────────────────────────
    # condition_type: threshold
    {
        'event_id': 'safety.aeb_activation',
        'category': 'safety',
        'description': 'Automatic Emergency Braking activated',
        'severity': Decimal('3'),
        'severity_hint': 'P1',
        'trigger_signal': 'AEBActivation',
        'signal_id': Decimal('44'),
        'condition_type': 'threshold',
        'threshold_operator': '>',
        'threshold_value': Decimal('0'),
        'detection': 'cloud',
        'edge_candidate': True,
        'scheme_name': 'cms-safety-aeb-activation',
        'applicableModels': ['CMS-FLEET-MODEL', 'BE6-V12-PROD', 'BE07-V13-DEV'],
        'applicableModelsUpdatedAt': '2026-05-20T16:42:27.756741+00:00',
    },
    {
        'event_id': 'safety.esc_activation',
        'category': 'safety',
        'description': 'Electronic Stability Control activated',
        'severity': Decimal('2'),
        'severity_hint': 'P2',
        'trigger_signal': 'ESCActivation',
        'signal_id': Decimal('46'),
        'condition_type': 'threshold',
        'threshold_operator': '>',
        'threshold_value': Decimal('0'),
        'detection': 'cloud',
        'edge_candidate': True,
        'scheme_name': 'cms-safety-esc-activation',
        'applicableModels': ['CMS-FLEET-MODEL', 'BE6-V12-PROD', 'BE07-V13-DEV'],
        'applicableModelsUpdatedAt': '2026-05-20T16:42:27.877106+00:00',
    },
    {
        'event_id': 'safety.harsh_acceleration',
        'category': 'safety',
        'description': 'Sudden hard acceleration event',
        'severity': Decimal('1'),
        'severity_hint': 'P3',
        'trigger_signal': 'HarshAcceleration',
        'signal_id': Decimal('41'),
        'condition_type': 'threshold',
        'threshold_operator': '>',
        'threshold_value': Decimal('0.35'),
        'json_fields': ['acceleration'],
        'detection': 'cloud',
        'edge_candidate': True,
        'scheme_name': 'cms-safety-harsh-accel',
        'applicableModels': ['CMS-FLEET-MODEL', 'BE6-V12-PROD', 'BE07-V13-DEV'],
        'applicableModelsUpdatedAt': '2026-05-20T16:42:27.676817+00:00',
    },
    {
        'event_id': 'safety.harsh_braking',
        'category': 'safety',
        'description': 'Sudden hard braking event',
        'severity': Decimal('1'),
        'severity_hint': 'P3',
        'trigger_signal': 'HarshBraking',
        'signal_id': Decimal('40'),
        'condition_type': 'threshold',
        'threshold_operator': '>',
        'threshold_value': Decimal('0.4'),
        'json_fields': ['deceleration'],
        'detection': 'cloud',
        'edge_candidate': True,
        'scheme_name': 'cms-safety-harsh-braking',
        'applicableModels': ['CMS-FLEET-MODEL', 'BE6-V12-PROD', 'BE07-V13-DEV'],
        'applicableModelsUpdatedAt': '2026-05-20T16:42:27.915858+00:00',
    },
    {
        'event_id': 'safety.harsh_cornering',
        'category': 'safety',
        'description': 'Aggressive cornering / harsh turn',
        'severity': Decimal('1'),
        'severity_hint': 'P3',
        'trigger_signal': 'HarshTurn',
        'signal_id': Decimal('42'),
        'condition_type': 'threshold',
        'threshold_operator': '>',
        'threshold_value': Decimal('45'),
        'json_fields': ['harsh_turn'],
        'detection': 'cloud',
        'edge_candidate': True,
        'scheme_name': 'cms-safety-harsh-cornering',
        'applicableModels': ['CMS-FLEET-MODEL', 'BE6-V12-PROD', 'BE07-V13-DEV'],
        'applicableModelsUpdatedAt': '2026-05-20T16:42:27.458296+00:00',
    },
    {
        'event_id': 'safety.lane_departure',
        'category': 'safety',
        'description': 'Unintended lane departure detected via lateral G',
        'severity': Decimal('2'),
        'severity_hint': 'P2',
        'trigger_signal': 'LateralG',
        'signal_id': Decimal('76'),
        'condition_type': 'threshold',
        'threshold_operator': '>',
        'threshold_value': Decimal('5'),
        'detection': 'cloud',
        'edge_candidate': True,
        'scheme_name': 'cms-safety-lane-departure',
        'applicableModels': ['CMS-FLEET-MODEL', 'BE6-V12-PROD', 'BE07-V13-DEV'],
        'applicableModelsUpdatedAt': '2026-05-20T16:42:27.537876+00:00',
    },
    {
        'event_id': 'safety.speeding',
        'category': 'safety',
        'description': 'Vehicle exceeding speed threshold',
        'severity': Decimal('2'),
        'severity_hint': 'P2',
        'trigger_signal': 'VehicleSpeed',
        'signal_id': Decimal('1'),
        'condition_type': 'threshold',
        'threshold_operator': '>',
        'threshold_value': Decimal('80'),
        'json_fields': ['speed'],
        'detection': 'cloud',
        'edge_candidate': True,
        'scheme_name': 'cms-safety-speeding',
        'applicableModels': ['CMS-FLEET-MODEL', 'BE6-V12-PROD', 'BE07-V13-DEV'],
        'applicableModelsUpdatedAt': '2026-05-20T16:42:27.973384+00:00',
    },
    # condition_type: simple
    {
        'event_id': 'safety.collision_detected',
        'category': 'safety',
        'description': 'Collision detected — driver may be injured, stay in vehicle and call emergency services',
        'severity': Decimal('4'),
        'severity_hint': 'P0',
        'trigger_signal': 'ForwardCollisionWarning',
        'condition_type': 'simple',
        'threshold_operator': '=',
        'threshold_value': Decimal('1'),
        'duration_ms': Decimal('0'),
        'json_fields': ['forward_collision_warning', 'ForwardCollisionWarning'],
        'detection': 'cloud',
        'edge_candidate': False,
        'dtc_code': 'U3000_CRASH',
        'applicableModels': ['CMS-FLEET-MODEL', 'BE6-V12-PROD', 'BE07-V13-DEV'],
        'applicableModelsUpdatedAt': '2026-05-20T16:42:27.776231+00:00',
    },
    # condition_type: composite
    {
        'event_id': 'safety.drowsy_driving',
        'category': 'safety',
        'description': 'Erratic steering pattern indicating driver fatigue',
        'severity': Decimal('3'),
        'severity_hint': 'P1',
        'trigger_signal': 'LateralG',
        'signal_id': Decimal('76'),
        'condition_type': 'composite',
        'threshold_operator': '>',
        'threshold_value': Decimal('1'),
        'duration_ms': Decimal('30000'),
        'detection': 'cloud',
        'edge_candidate': False,
        'composite_condition': {
            'conditions': [
                {
                    'json_fields': ['lateral_g', 'LateralG'],
                    'signal': 'lateral_g',
                    'value': Decimal('1'),
                    'operator': '>',
                },
                {
                    'json_fields': ['speed'],
                    'signal': 'speed',
                    'value': Decimal('60'),
                    'operator': '>',
                },
            ],
            'logic': 'AND',
        },
        'applicableModels': ['CMS-FLEET-MODEL', 'BE6-V12-PROD', 'BE07-V13-DEV'],
        'applicableModelsUpdatedAt': '2026-05-20T16:42:27.835974+00:00',
    },
    {
        'event_id': 'safety.phone_usage',
        'category': 'safety',
        'description': 'Phone usage while driving',
        'severity': Decimal('2'),
        'severity_hint': 'P2',
        'trigger_signal': 'PhoneUsage',
        'signal_id': Decimal('50'),
        'condition_type': 'composite',
        'threshold_operator': '=',
        'threshold_value': Decimal('1'),
        'duration_ms': Decimal('10000'),
        'json_fields': ['phone_use', 'driverPhoneUsage'],
        'detection': 'cloud',
        'edge_candidate': False,
        'composite_condition': {
            'conditions': [
                {
                    'json_fields': ['phone_use', 'driverPhoneUsage'],
                    'signal': 'phone_use',
                    'value': Decimal('1'),
                    'operator': '=',
                },
                {
                    'json_fields': ['speed'],
                    'signal': 'speed',
                    'value': Decimal('5'),
                    'operator': '>',
                },
            ],
            'logic': 'AND',
        },
        'applicableModels': ['CMS-FLEET-MODEL', 'BE6-V12-PROD', 'BE07-V13-DEV'],
        'applicableModelsUpdatedAt': '2026-05-20T16:42:27.312527+00:00',
    },
    {
        'event_id': 'safety.seatbelt_unfastened',
        'category': 'safety',
        'description': 'Seatbelt unfastened while vehicle in motion',
        'severity': Decimal('1'),
        'severity_hint': 'P3',
        'trigger_signal': 'SeatbeltViolation',
        'signal_id': Decimal('51'),
        'condition_type': 'composite',
        'threshold_operator': '=',
        'threshold_value': Decimal('1'),
        'detection': 'cloud',
        'edge_candidate': False,
        'composite_condition': {
            'conditions': [
                {
                    'json_fields': ['seatbelt_violation', 'SeatbeltViolation'],
                    'signal': 'seatbelt_violation',
                    'value': Decimal('1'),
                    'operator': '=',
                },
                {
                    'json_fields': ['speed'],
                    'signal': 'speed',
                    'value': Decimal('5'),
                    'operator': '>',
                },
            ],
            'logic': 'AND',
        },
        'applicableModels': ['CMS-FLEET-MODEL', 'BE6-V12-PROD', 'BE07-V13-DEV'],
        'applicableModelsUpdatedAt': '2026-05-20T16:42:27.856391+00:00',
    },
    {
        'event_id': 'safety.tailgating',
        'category': 'safety',
        'description': 'Following distance too close at speed',
        'severity': Decimal('2'),
        'severity_hint': 'P2',
        'trigger_signal': 'FollowingDistance',
        'signal_id': Decimal('77'),
        'condition_type': 'composite',
        'threshold_operator': '<',
        'threshold_value': Decimal('2'),
        'detection': 'cloud',
        'edge_candidate': False,
        'composite_condition': {
            'conditions': [
                {
                    'json_fields': ['following_distance', 'FollowingDistance'],
                    'signal': 'following_distance',
                    'value': Decimal('2'),
                    'operator': '<',
                },
                {
                    'json_fields': ['speed'],
                    'signal': 'speed',
                    'value': Decimal('30'),
                    'operator': '>',
                },
            ],
            'logic': 'AND',
        },
        'applicableModels': ['CMS-FLEET-MODEL', 'BE6-V12-PROD', 'BE07-V13-DEV'],
        'applicableModelsUpdatedAt': '2026-05-20T16:42:27.716668+00:00',
    },
    {
        'event_id': 'safety.unsafe_lane_change',
        'category': 'safety',
        'description': 'Lane change without turn signal at speed',
        'severity': Decimal('2'),
        'severity_hint': 'P2',
        'trigger_signal': 'LateralG',
        'signal_id': Decimal('76'),
        'condition_type': 'composite',
        'threshold_operator': '>',
        'threshold_value': Decimal('3'),
        'detection': 'cloud',
        'edge_candidate': False,
        'composite_condition': {
            'conditions': [
                {
                    'json_fields': ['lateral_g', 'LateralG'],
                    'signal': 'lateral_g',
                    'value': Decimal('3'),
                    'operator': '>',
                },
                {
                    'json_fields': ['turn_signal', 'TurnSignalActive'],
                    'signal': 'turn_signal',
                    'value': Decimal('0'),
                    'operator': '=',
                },
                {
                    'json_fields': ['speed'],
                    'signal': 'speed',
                    'value': Decimal('40'),
                    'operator': '>',
                },
            ],
            'logic': 'AND',
        },
        'applicableModels': ['CMS-FLEET-MODEL', 'BE6-V12-PROD', 'BE07-V13-DEV'],
        'applicableModelsUpdatedAt': '2026-05-20T16:42:27.637476+00:00',
    },

    # ── MAINTENANCE events ──────────────────────────────────────
    # condition_type: simple
    {
        'event_id': 'maintenance.brake_system_fault',
        'category': 'maintenance',
        'description': 'Brake system fault — stop driving, do not operate vehicle',
        'severity': Decimal('4'),
        'severity_hint': 'P0',
        'trigger_signal': 'BrakeSystemStatus',
        'condition_type': 'simple',
        'threshold_operator': '=',
        'threshold_value': Decimal('1'),
        'json_fields': ['brake_system_fault', 'brake_fault_active'],
        'detection': 'cloud',
        'edge_candidate': False,
        'dtc_code': 'C1234',
        'applicableModels': ['CMS-FLEET-MODEL', 'BE6-V12-PROD', 'BE07-V13-DEV'],
        'applicableModelsUpdatedAt': '2026-05-20T16:42:27.578507+00:00',
    },
    {
        'event_id': 'maintenance.brake_wear',
        'category': 'maintenance',
        'description': 'Brake pad wear exceeding threshold',
        'severity': Decimal('2'),
        'severity_hint': 'P2',
        'trigger_signal': 'BrakeWear',
        'condition_type': 'simple',
        'threshold_operator': '>',
        'threshold_value': Decimal('80'),
        'detection': 'cloud',
        'edge_candidate': False,
        'dtc_code': 'C1213',
        'dtc_code_promoted_at': '2026-05-04T15:21:15.381777Z',
        'dtc_code_source': 'promoted-2026-05-04',
        'applicableModels': ['CMS-FLEET-MODEL', 'BE6-V12-PROD', 'BE07-V13-DEV'],
        'applicableModelsUpdatedAt': '2026-05-20T16:42:27.617982+00:00',
    },
    {
        'event_id': 'maintenance.camshaft_sensor_fault',
        'category': 'maintenance',
        'description': 'Camshaft position sensor circuit fault — engine stall risk',
        'severity': Decimal('3'),
        'severity_hint': 'P1',
        'trigger_signal': 'CamshaftSensorStatus',
        'condition_type': 'simple',
        'threshold_operator': '=',
        'threshold_value': Decimal('1'),
        'json_fields': ['camshaft_sensor_fault'],
        'detection': 'cloud',
        'edge_candidate': False,
        'dtc_code': 'P0340',
        'applicableModels': ['CMS-FLEET-MODEL'],
        'applicableModelsUpdatedAt': '2026-05-20T16:42:27.816568+00:00',
    },
    {
        'event_id': 'maintenance.catalyst_efficiency_low',
        'category': 'maintenance',
        'description': 'Catalytic converter efficiency below threshold — emissions issue',
        'severity': Decimal('2'),
        'severity_hint': 'P2',
        'trigger_signal': 'CatalystEfficiency',
        'condition_type': 'simple',
        'threshold_operator': '<',
        'threshold_value': Decimal('85'),
        'json_fields': ['catalyst_efficiency'],
        'detection': 'cloud',
        'edge_candidate': False,
        'dtc_code': 'P0420',
        'applicableModels': ['CMS-FLEET-MODEL'],
        'applicableModelsUpdatedAt': '2026-05-20T16:42:27.499755+00:00',
    },
    {
        'event_id': 'maintenance.coolant_critical_overheat',
        'category': 'maintenance',
        'description': 'Engine coolant critically overheated — stop driving, let engine cool',
        'severity': Decimal('4'),
        'severity_hint': 'P0',
        'trigger_signal': 'CoolantTemp',
        'condition_type': 'simple',
        'threshold_operator': '>',
        'threshold_value': Decimal('125'),
        'json_fields': ['coolant_temp'],
        'detection': 'cloud',
        'edge_candidate': False,
        'dtc_code': 'P0217',
        'applicableModels': ['CMS-FLEET-MODEL', 'BE6-V12-PROD', 'BE07-V13-DEV'],
        'applicableModelsUpdatedAt': '2026-05-20T16:42:27.336603+00:00',
    },
    {
        'event_id': 'maintenance.ecu_internal_flag',
        'category': 'maintenance',
        'description': 'ECU internal diagnostic flag set — monitor only',
        'severity': Decimal('1'),
        'severity_hint': 'P3',
        'trigger_signal': 'ECUInternalStatus',
        'condition_type': 'simple',
        'threshold_operator': '=',
        'threshold_value': Decimal('1'),
        'json_fields': ['ecu_internal_flag'],
        'detection': 'cloud',
        'edge_candidate': False,
        'dtc_code': 'B1000',
        'applicableModels': ['CMS-FLEET-MODEL', 'BE6-V12-PROD', 'BE07-V13-DEV'],
        'applicableModelsUpdatedAt': '2026-05-20T16:42:28.130377+00:00',
    },
    {
        'event_id': 'maintenance.engine_misfire_severe',
        'category': 'maintenance',
        'description': 'Severe engine misfire — catalytic converter damage imminent',
        'severity': Decimal('3'),
        'severity_hint': 'P1',
        'trigger_signal': 'MisfireCount',
        'condition_type': 'simple',
        'threshold_operator': '>',
        'threshold_value': Decimal('50'),
        'json_fields': ['misfire_count'],
        'detection': 'cloud',
        'edge_candidate': False,
        'dtc_code': 'P0300',
        'applicableModels': ['CMS-FLEET-MODEL'],
        'applicableModelsUpdatedAt': '2026-05-20T16:42:27.290833+00:00',
    },
    {
        'event_id': 'maintenance.engine_overspeed',
        'category': 'maintenance',
        'description': 'Engine RPM exceeding safe limit',
        'severity': Decimal('3'),
        'severity_hint': 'P1',
        'trigger_signal': 'EngineRPM',
        'condition_type': 'simple',
        'threshold_operator': '>',
        'threshold_value': Decimal('6500'),
        'detection': 'cloud',
        'edge_candidate': False,
        'dtc_code': 'P0219',
        'dtc_code_promoted_at': '2026-05-04T15:21:15.381777Z',
        'dtc_code_source': 'promoted-2026-05-04',
        'applicableModels': ['CMS-FLEET-MODEL'],
        'applicableModelsUpdatedAt': '2026-05-20T16:42:27.597803+00:00',
    },
    {
        'event_id': 'maintenance.ev_battery_thermal_event',
        'category': 'maintenance',
        'description': 'EV high-voltage battery thermal event — stop driving immediately, evacuate',
        'severity': Decimal('4'),
        'severity_hint': 'P0',
        'trigger_signal': 'BatteryTempMax',
        'condition_type': 'simple',
        'threshold_operator': '>',
        'threshold_value': Decimal('60'),
        'json_fields': ['battery_temp_max'],
        'detection': 'cloud',
        'edge_candidate': False,
        'dtc_code': 'P0A80',
        'applicableModels': ['CMS-FLEET-MODEL', 'BE6-V12-PROD', 'BE07-V13-DEV'],
        'applicableModelsUpdatedAt': '2026-05-20T16:42:27.657584+00:00',
    },
    {
        'event_id': 'maintenance.filter_replacement',
        'category': 'maintenance',
        'description': 'Air filter life remaining below threshold',
        'severity': Decimal('1'),
        'severity_hint': 'P3',
        'trigger_signal': 'FilterLife',
        'condition_type': 'simple',
        'threshold_operator': '<',
        'threshold_value': Decimal('10'),
        'detection': 'cloud',
        'edge_candidate': False,
        'applicableModels': ['CMS-FLEET-MODEL', 'BE6-V12-PROD', 'BE07-V13-DEV'],
        'applicableModelsUpdatedAt': '2026-05-20T16:42:27.934895+00:00',
    },
    {
        'event_id': 'maintenance.high_engine_temp',
        'category': 'maintenance',
        'description': 'Engine temperature critically high',
        'severity': Decimal('3'),
        'severity_hint': 'P1',
        'trigger_signal': 'EngineTemp',
        'condition_type': 'simple',
        'threshold_operator': '>',
        'threshold_value': Decimal('110'),
        'detection': 'cloud',
        'edge_candidate': False,
        'dtc_code': 'P0118',
        'dtc_code_promoted_at': '2026-05-04T15:21:15.381777Z',
        'dtc_code_source': 'promoted-2026-05-04',
        'applicableModels': ['CMS-FLEET-MODEL'],
        'applicableModelsUpdatedAt': '2026-05-20T16:42:28.032735+00:00',
    },
    {
        'event_id': 'maintenance.invalid_data_from_ecm',
        'category': 'maintenance',
        'description': 'Invalid data received from ECM — intermittent comm issue',
        'severity': Decimal('2'),
        'severity_hint': 'P2',
        'trigger_signal': 'ECMDataValid',
        'condition_type': 'simple',
        'threshold_operator': '=',
        'threshold_value': Decimal('0'),
        'json_fields': ['ecm_data_valid'],
        'detection': 'cloud',
        'edge_candidate': False,
        'dtc_code': 'U0401',
        'applicableModels': ['CMS-FLEET-MODEL'],
        'applicableModelsUpdatedAt': '2026-05-20T16:42:28.071756+00:00',
    },
    {
        'event_id': 'maintenance.lean_fuel_mixture',
        'category': 'maintenance',
        'description': 'Air/fuel mixture too lean on bank 1 — reduced fuel economy',
        'severity': Decimal('2'),
        'severity_hint': 'P2',
        'trigger_signal': 'FuelMixtureBank1',
        'condition_type': 'simple',
        'threshold_operator': '<',
        'threshold_value': Decimal('14'),
        'json_fields': ['fuel_mixture_bank1'],
        'detection': 'cloud',
        'edge_candidate': False,
        'dtc_code': 'P0171',
        'applicableModels': ['CMS-FLEET-MODEL'],
        'applicableModelsUpdatedAt': '2026-05-20T16:42:27.395801+00:00',
    },
    {
        'event_id': 'maintenance.lost_comm_pcm',
        'category': 'maintenance',
        'description': 'Lost communication with powertrain control module',
        'severity': Decimal('3'),
        'severity_hint': 'P1',
        'trigger_signal': 'PCMCommStatus',
        'condition_type': 'simple',
        'threshold_operator': '=',
        'threshold_value': Decimal('0'),
        'json_fields': ['pcm_comm_status'],
        'detection': 'cloud',
        'edge_candidate': False,
        'dtc_code': 'U0100',
        'applicableModels': ['CMS-FLEET-MODEL'],
        'applicableModelsUpdatedAt': '2026-05-20T16:42:27.953865+00:00',
    },
    {
        'event_id': 'maintenance.low_battery',
        'category': 'maintenance',
        'description': 'Battery voltage below safe threshold',
        'severity': Decimal('2'),
        'severity_hint': 'P2',
        'trigger_signal': 'BatteryVoltage',
        'condition_type': 'simple',
        'threshold_operator': '<',
        'threshold_value': Decimal('12'),
        'detection': 'cloud',
        'edge_candidate': False,
        'applicableModels': ['CMS-FLEET-MODEL', 'BE6-V12-PROD', 'BE07-V13-DEV'],
        'applicableModelsUpdatedAt': '2026-05-20T16:42:27.896419+00:00',
    },
    {
        'event_id': 'maintenance.low_brake_fluid',
        'category': 'maintenance',
        'description': 'Brake fluid low — limited driving until serviced',
        'severity': Decimal('3'),
        'severity_hint': 'P1',
        'trigger_signal': 'BrakeFluidLevel',
        'condition_type': 'simple',
        'threshold_operator': '<',
        'threshold_value': Decimal('20'),
        'json_fields': ['brake_fluid_level'],
        'detection': 'cloud',
        'edge_candidate': False,
        'dtc_code': 'C1241',
        'applicableModels': ['CMS-FLEET-MODEL', 'BE6-V12-PROD', 'BE07-V13-DEV'],
        'applicableModelsUpdatedAt': '2026-05-20T16:42:27.992956+00:00',
    },
    {
        'event_id': 'maintenance.low_fuel',
        'category': 'maintenance',
        'description': 'Fuel level critically low',
        'severity': Decimal('1'),
        'severity_hint': 'P3',
        'trigger_signal': 'FuelLevel',
        'condition_type': 'simple',
        'threshold_operator': '<',
        'threshold_value': Decimal('5'),
        'detection': 'cloud',
        'edge_candidate': False,
        'dtc_code': 'P0461',
        'applicableModels': ['CMS-FLEET-MODEL'],
        'applicableModelsUpdatedAt': '2026-05-20T16:42:27.356149+00:00',
    },
    {
        'event_id': 'maintenance.low_oil_pressure',
        'category': 'maintenance',
        'description': 'Engine oil pressure below safe threshold',
        'severity': Decimal('2'),
        'severity_hint': 'P2',
        'trigger_signal': 'OilPressure',
        'condition_type': 'simple',
        'threshold_operator': '<',
        'threshold_value': Decimal('20'),
        'detection': 'cloud',
        'edge_candidate': False,
        'dtc_code': 'P0520',
        'dtc_code_promoted_at': '2026-05-04T15:21:15.381777Z',
        'dtc_code_source': 'promoted-2026-05-04',
        'applicableModels': ['CMS-FLEET-MODEL'],
        'applicableModelsUpdatedAt': '2026-05-20T16:42:27.375736+00:00',
    },
    {
        'event_id': 'maintenance.oil_life_low',
        'category': 'maintenance',
        'description': 'Oil life remaining below threshold',
        'severity': Decimal('1'),
        'severity_hint': 'P3',
        'trigger_signal': 'OilLife',
        'condition_type': 'simple',
        'threshold_operator': '<',
        'threshold_value': Decimal('10'),
        'detection': 'cloud',
        'edge_candidate': False,
        'applicableModels': ['CMS-FLEET-MODEL'],
        'applicableModelsUpdatedAt': '2026-05-20T16:42:28.110876+00:00',
    },
    {
        'event_id': 'maintenance.pcm_processor_fault',
        'category': 'maintenance',
        'description': 'Powertrain control module processor fault — may cause stalling',
        'severity': Decimal('3'),
        'severity_hint': 'P1',
        'trigger_signal': 'PCMStatus',
        'condition_type': 'simple',
        'threshold_operator': '=',
        'threshold_value': Decimal('1'),
        'json_fields': ['pcm_fault_active'],
        'detection': 'cloud',
        'edge_candidate': False,
        'dtc_code': 'P0606',
        'applicableModels': ['CMS-FLEET-MODEL'],
        'applicableModelsUpdatedAt': '2026-05-20T16:42:27.419156+00:00',
    },
    {
        'event_id': 'maintenance.small_evap_leak',
        'category': 'maintenance',
        'description': 'Small evaporative emissions leak detected',
        'severity': Decimal('1'),
        'severity_hint': 'P3',
        'trigger_signal': 'EvapLeakDetected',
        'condition_type': 'simple',
        'threshold_operator': '=',
        'threshold_value': Decimal('1'),
        'json_fields': ['evap_leak_detected'],
        'detection': 'cloud',
        'edge_candidate': False,
        'dtc_code': 'P0442',
        'applicableModels': ['CMS-FLEET-MODEL'],
        'applicableModelsUpdatedAt': '2026-05-20T16:42:27.696326+00:00',
    },
    {
        'event_id': 'maintenance.system_voltage_low_minor',
        'category': 'maintenance',
        'description': 'System voltage slightly low — alternator degrading',
        'severity': Decimal('1'),
        'severity_hint': 'P3',
        'trigger_signal': 'BatteryVoltage',
        'condition_type': 'simple',
        'threshold_operator': '<',
        'threshold_value': Decimal('12.4'),
        'json_fields': ['batteryVoltage'],
        'detection': 'cloud',
        'edge_candidate': False,
        'dtc_code': 'P0562',
        'applicableModels': ['CMS-FLEET-MODEL', 'BE6-V12-PROD', 'BE07-V13-DEV'],
        'applicableModelsUpdatedAt': '2026-05-20T16:42:27.438714+00:00',
    },
    {
        'event_id': 'maintenance.thermal_runaway',
        'category': 'maintenance',
        'description': 'Thermal runaway detected — engine compartment fire risk, exit vehicle immediately',
        'severity': Decimal('4'),
        'severity_hint': 'P0',
        'trigger_signal': 'CoolantTemp',
        'condition_type': 'simple',
        'threshold_operator': '>',
        'threshold_value': Decimal('200'),
        'duration_ms': Decimal('0'),
        'json_fields': ['coolant_temp', 'CoolantTemp'],
        'detection': 'cloud',
        'edge_candidate': False,
        'dtc_code': 'B0001_FIRE',
        'applicableModels': ['CMS-FLEET-MODEL', 'BE6-V12-PROD', 'BE07-V13-DEV'],
        'applicableModelsUpdatedAt': '2026-05-20T16:42:27.795861+00:00',
    },
    {
        'event_id': 'maintenance.tire_pressure',
        'category': 'maintenance',
        'description': 'Tire pressure below safe threshold',
        'severity': Decimal('2'),
        'severity_hint': 'P2',
        'trigger_signal': 'TirePressureFL',
        'json_fields': ['tire_pressure_fl'],
        'condition_type': 'simple',
        'threshold_operator': '<',
        'threshold_value': Decimal('28'),
        'detection': 'cloud',
        'edge_candidate': False,
        'applicableModels': ['CMS-FLEET-MODEL', 'BE6-V12-PROD', 'BE07-V13-DEV'],
        'applicableModelsUpdatedAt': '2026-05-20T16:42:28.012409+00:00',
    },
    {
        'event_id': 'maintenance.tire_tread_low',
        'category': 'maintenance',
        'description': 'Tire tread depth below safe minimum',
        'severity': Decimal('2'),
        'severity_hint': 'P2',
        'trigger_signal': 'TireTreadFL',
        'condition_type': 'simple',
        'threshold_operator': '<',
        'threshold_value': Decimal('3'),
        'detection': 'cloud',
        'edge_candidate': False,
        'applicableModels': ['CMS-FLEET-MODEL', 'BE6-V12-PROD', 'BE07-V13-DEV'],
        'applicableModelsUpdatedAt': '2026-05-20T16:42:27.479249+00:00',
    },
    {
        'event_id': 'maintenance.traction_control_fault',
        'category': 'maintenance',
        'description': 'Traction control / stability system disabled — reduced safety at speed',
        'severity': Decimal('3'),
        'severity_hint': 'P1',
        'trigger_signal': 'TractionControlStatus',
        'condition_type': 'simple',
        'threshold_operator': '=',
        'threshold_value': Decimal('1'),
        'json_fields': ['traction_control_fault'],
        'detection': 'cloud',
        'edge_candidate': False,
        'dtc_code': 'C1201',
        'applicableModels': ['CMS-FLEET-MODEL', 'BE6-V12-PROD', 'BE07-V13-DEV'],
        'applicableModelsUpdatedAt': '2026-05-20T16:42:27.737202+00:00',
    },
    {
        'event_id': 'maintenance.transmission_failure',
        'category': 'maintenance',
        'description': 'Transmission failure with limp mode — stop driving, tow required',
        'severity': Decimal('4'),
        'severity_hint': 'P0',
        'trigger_signal': 'TransmissionStatus',
        'condition_type': 'simple',
        'threshold_operator': '=',
        'threshold_value': Decimal('1'),
        'json_fields': ['transmission_fault_active'],
        'detection': 'cloud',
        'edge_candidate': False,
        'dtc_code': 'P0700',
        'applicableModels': ['CMS-FLEET-MODEL'],
        'applicableModelsUpdatedAt': '2026-05-20T16:42:27.518616+00:00',
    },
    {
        'event_id': 'maintenance.turbo_underboost',
        'category': 'maintenance',
        'description': 'Turbo/supercharger underboost — reduced power, continue with caution',
        'severity': Decimal('3'),
        'severity_hint': 'P1',
        'trigger_signal': 'TurboBoost',
        'condition_type': 'simple',
        'threshold_operator': '<',
        'threshold_value': Decimal('5'),
        'duration_ms': Decimal('0'),
        'json_fields': ['turbo_boost', 'TurboBoost'],
        'detection': 'cloud',
        'edge_candidate': False,
        'dtc_code': 'P0299',
        'applicableModels': ['CMS-FLEET-MODEL'],
        'applicableModelsUpdatedAt': '2026-05-20T16:42:27.558990+00:00',
    },
    {
        'event_id': 'maintenance.wheel_speed_sensor_lf',
        'category': 'maintenance',
        'description': 'Left-front wheel speed sensor circuit issue — ABS degraded',
        'severity': Decimal('2'),
        'severity_hint': 'P2',
        'trigger_signal': 'WheelSpeedSensorLF',
        'condition_type': 'simple',
        'threshold_operator': '=',
        'threshold_value': Decimal('1'),
        'json_fields': ['wheel_speed_sensor_lf_fault'],
        'detection': 'cloud',
        'edge_candidate': False,
        'dtc_code': 'C0035',
        'applicableModels': ['CMS-FLEET-MODEL', 'BE6-V12-PROD', 'BE07-V13-DEV'],
        'applicableModelsUpdatedAt': '2026-05-20T16:42:28.051935+00:00',
    },
    {
        'event_id': 'maintenance.wheel_speed_sensor_rf',
        'category': 'maintenance',
        'description': 'Right-front wheel speed sensor circuit issue — ABS degraded',
        'severity': Decimal('2'),
        'severity_hint': 'P2',
        'trigger_signal': 'WheelSpeedSensorRF',
        'condition_type': 'simple',
        'threshold_operator': '=',
        'threshold_value': Decimal('1'),
        'json_fields': ['wheel_speed_sensor_rf_fault'],
        'detection': 'cloud',
        'edge_candidate': False,
        'dtc_code': 'C0040',
        'applicableModels': ['CMS-FLEET-MODEL', 'BE6-V12-PROD', 'BE07-V13-DEV'],
        'applicableModelsUpdatedAt': '2026-05-20T16:42:28.091382+00:00',
    },
]



# ── OEM1 catalog additions (A2.2 of spec 2026-06-01-cms-oem1-transform-manifest-staging-e2e) ──
# 13 new events + 2 new categories added to CMS BASE catalog (not OEM1-only).
# Uses conditional put (attribute_not_exists) for idempotency.
OEM1_EVENTS = [
    # ── maintenance ──────────────────────────────────────────────────────
    {
        'event_id': 'maintenance.washer_fluid_low',
        'category': 'maintenance',
        'description': 'Windshield washer fluid level critically low',
        'severity': Decimal('1'),
        'severity_hint': 'P3',
        'trigger_signal': 'WasherFluidLevel',
        'condition_type': 'simple',
        'threshold_operator': '<',
        'threshold_value': Decimal('10'),
        'detection': 'cloud',
        'edge_candidate': False,
    },
    {
        'event_id': 'maintenance.trailer_brake_disconnected',
        'category': 'maintenance',
        'description': 'Trailer brake connection lost or disconnected',
        'severity': Decimal('3'),
        'severity_hint': 'P1',
        'trigger_signal': 'TrailerBrakeStatus',
        'condition_type': 'simple',
        'threshold_operator': '=',
        'threshold_value': Decimal('0'),
        'detection': 'cloud',
        'edge_candidate': False,
        'dtc_code': 'C0091',
    },
    {
        'event_id': 'maintenance.check_engine_light',
        'category': 'maintenance',
        'description': 'Check engine / malfunction indicator lamp illuminated',
        'severity': Decimal('2'),
        'severity_hint': 'P2',
        'trigger_signal': 'MILStatus',
        'condition_type': 'simple',
        'threshold_operator': '=',
        'threshold_value': Decimal('1'),
        'detection': 'cloud',
        'edge_candidate': False,
        'dtc_code': 'P0001',
    },
    {
        'event_id': 'maintenance.def_level_low',
        'category': 'maintenance',
        'description': 'Diesel exhaust fluid (DEF/AdBlue) level critically low',
        'severity': Decimal('2'),
        'severity_hint': 'P2',
        'trigger_signal': 'DEFLevel',
        'condition_type': 'simple',
        'threshold_operator': '<',
        'threshold_value': Decimal('10'),
        'detection': 'cloud',
        'edge_candidate': False,
        'dtc_code': 'P205B',
    },
    {
        'event_id': 'maintenance.powertrain_malfunction',
        'category': 'maintenance',
        'description': 'Powertrain malfunction indicator — reduced performance mode active',
        'severity': Decimal('3'),
        'severity_hint': 'P1',
        'trigger_signal': 'PowertrainMalfunctionStatus',
        'condition_type': 'simple',
        'threshold_operator': '=',
        'threshold_value': Decimal('1'),
        'detection': 'cloud',
        'edge_candidate': False,
        'dtc_code': 'P0607',
    },
    {
        'event_id': 'maintenance.charge_system_fault',
        'category': 'maintenance',
        'description': 'Charging system fault — alternator or belt issue detected',
        'severity': Decimal('2'),
        'severity_hint': 'P2',
        'trigger_signal': 'ChargeSystemStatus',
        'condition_type': 'simple',
        'threshold_operator': '=',
        'threshold_value': Decimal('1'),
        'detection': 'cloud',
        'edge_candidate': False,
        'dtc_code': 'P0620',
    },
    {
        'event_id': 'maintenance.water_in_fuel',
        'category': 'maintenance',
        'description': 'Water detected in fuel system — drain before operation',
        'severity': Decimal('3'),
        'severity_hint': 'P1',
        'trigger_signal': 'WaterInFuelStatus',
        'condition_type': 'simple',
        'threshold_operator': '=',
        'threshold_value': Decimal('1'),
        'detection': 'cloud',
        'edge_candidate': False,
        'dtc_code': 'P0093',
    },
    # ── safety ────────────────────────────────────────────────────────────
    {
        'event_id': 'safety.airbag_warning',
        'category': 'safety',
        'description': 'Airbag / supplemental restraint system fault — do not disable airbags',
        'severity': Decimal('3'),
        'severity_hint': 'P1',
        'trigger_signal': 'AirbagSystemStatus',
        'condition_type': 'simple',
        'threshold_operator': '=',
        'threshold_value': Decimal('1'),
        'detection': 'cloud',
        'edge_candidate': False,
        'dtc_code': 'B0001',
    },
    {
        'event_id': 'safety.antilock_brake_fault',
        'category': 'safety',
        'description': 'Anti-lock braking system fault — braking distances may increase',
        'severity': Decimal('3'),
        'severity_hint': 'P1',
        'trigger_signal': 'ABSFaultStatus',
        'condition_type': 'simple',
        'threshold_operator': '=',
        'threshold_value': Decimal('1'),
        'detection': 'cloud',
        'edge_candidate': False,
        'dtc_code': 'C0035',
    },
    {
        'event_id': 'safety.service_steering',
        'category': 'safety',
        'description': 'Electric power steering fault — increased steering effort required',
        'severity': Decimal('3'),
        'severity_hint': 'P1',
        'trigger_signal': 'SteeringSystemStatus',
        'condition_type': 'simple',
        'threshold_operator': '=',
        'threshold_value': Decimal('1'),
        'detection': 'cloud',
        'edge_candidate': False,
        'dtc_code': 'C0460',
    },
    {
        'event_id': 'safety.lighting_system_failure',
        'category': 'safety',
        'description': 'Exterior lighting system failure — headlight, brake light, or turn signal out',
        'severity': Decimal('2'),
        'severity_hint': 'P2',
        'trigger_signal': 'LightingSystemStatus',
        'condition_type': 'simple',
        'threshold_operator': '=',
        'threshold_value': Decimal('1'),
        'detection': 'cloud',
        'edge_candidate': False,
        'dtc_code': 'B1004',
    },
    # ── commercial (NEW CATEGORY) ─────────────────────────────────────────
    {
        'event_id': 'commercial.power_take_off_engaged',
        'category': 'commercial',
        'description': 'Power take-off (PTO) engaged — equipment operating from vehicle drive system',
        'severity': Decimal('1'),
        'severity_hint': 'P3',
        'trigger_signal': 'PowerTakeOffStatus',
        'condition_type': 'simple',
        'threshold_operator': '=',
        'threshold_value': Decimal('1'),
        'detection': 'cloud',
        'edge_candidate': True,
    },
    {
        'event_id': 'commercial.excessive_idle',
        'category': 'commercial',
        'description': 'Excessive engine idle detected — exceeds fleet policy idle threshold',
        'severity': Decimal('1'),
        'severity_hint': 'P3',
        'trigger_signal': 'TotalEngineTimeIdle',
        'condition_type': 'threshold',
        'threshold_operator': '>',
        'threshold_value': Decimal('1800'),
        'detection': 'cloud',
        'edge_candidate': True,
    },
]


def seed():
    table = dynamodb.Table(TABLE)
    print(f"Seeding {len(EVENTS)} events → {TABLE}")
    for event in EVENTS:
        table.put_item(Item=event)
        print(f"  ✅ {event['event_id']}")
    print(f"\n✅ Event catalog seeded: {len(EVENTS)} events")


def seed_oem1_events():
    """Seed the 13 new OEM1 catalog-gap events idempotently.

    Uses attribute_not_exists condition to skip rows already present.
    Re-running this function is safe.
    """
    table = dynamodb.Table(TABLE)
    seeded = 0
    skipped = 0
    print(f"\nSeeding {len(OEM1_EVENTS)} OEM1 events → {TABLE}")
    for event in OEM1_EVENTS:
        try:
            table.put_item(
                Item=event,
                ConditionExpression='attribute_not_exists(event_id)',
            )
            seeded += 1
            print(f"  ✅ Seeded: {event['event_id']}")
        except dynamodb.meta.client.exceptions.ConditionalCheckFailedException:
            skipped += 1
            print(f"  ⏭  Already exists: {event['event_id']}")
    print(f"\n✅ OEM1 events: {seeded} seeded, {skipped} skipped (already present)")


if __name__ == '__main__':
    seed()
    seed_oem1_events()
