# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from autonomic.ext.command import command_pb2 as autonomic_dot_ext_dot_command_dot_command__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in autonomic/ext/command/command_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DeviceCommandStub(object):
    """RPC for upstream services to request that a connectivity device perform a command
    In this model, the device registers its willingness to perform commands as defined
    by this service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.registerCommandListener = channel.unary_stream(
                '/autonomic.ext.command.DeviceCommand/registerCommandListener',
                request_serializer=autonomic_dot_ext_dot_command_dot_command__pb2.RegisterCommandListenerRequest.SerializeToString,
                response_deserializer=autonomic_dot_ext_dot_command_dot_command__pb2.CommandTrigger.FromString,
                _registered_method=True)


class DeviceCommandServicer(object):
    """RPC for upstream services to request that a connectivity device perform a command
    In this model, the device registers its willingness to perform commands as defined
    by this service definition.
    """

    def registerCommandListener(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeviceCommandServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'registerCommandListener': grpc.unary_stream_rpc_method_handler(
                    servicer.registerCommandListener,
                    request_deserializer=autonomic_dot_ext_dot_command_dot_command__pb2.RegisterCommandListenerRequest.FromString,
                    response_serializer=autonomic_dot_ext_dot_command_dot_command__pb2.CommandTrigger.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'autonomic.ext.command.DeviceCommand', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('autonomic.ext.command.DeviceCommand', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DeviceCommand(object):
    """RPC for upstream services to request that a connectivity device perform a command
    In this model, the device registers its willingness to perform commands as defined
    by this service definition.
    """

    @staticmethod
    def registerCommandListener(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/autonomic.ext.command.DeviceCommand/registerCommandListener',
            autonomic_dot_ext_dot_command_dot_command__pb2.RegisterCommandListenerRequest.SerializeToString,
            autonomic_dot_ext_dot_command_dot_command__pb2.CommandTrigger.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
