# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: autonomic/ext/telemetry/dynamics.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'autonomic/ext/telemetry/dynamics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&autonomic/ext/telemetry/dynamics.proto\x12\x17\x61utonomic.ext.telemetry\"8\n\nQuaternion\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x12\t\n\x01w\x18\x04 \x01(\x01\"7\n\x0b\x45ulerAngles\x12\x0c\n\x04roll\x18\x01 \x01(\x01\x12\r\n\x05pitch\x18\x02 \x01(\x01\x12\x0b\n\x03yaw\x18\x03 \x01(\x01\"\x85\x01\n\x0eRotationMatrix\x12\x0b\n\x03m11\x18\x01 \x01(\x01\x12\x0b\n\x03m12\x18\x02 \x01(\x01\x12\x0b\n\x03m13\x18\x03 \x01(\x01\x12\x0b\n\x03m21\x18\x04 \x01(\x01\x12\x0b\n\x03m22\x18\x05 \x01(\x01\x12\x0b\n\x03m23\x18\x06 \x01(\x01\x12\x0b\n\x03m31\x18\x07 \x01(\x01\x12\x0b\n\x03m32\x18\x08 \x01(\x01\x12\x0b\n\x03m33\x18\t \x01(\x01\"\xd9\x01\n\x0bOrientation\x12\x39\n\nquaternion\x18\x01 \x01(\x0b\x32#.autonomic.ext.telemetry.QuaternionH\x00\x12<\n\x0c\x65uler_angles\x18\x02 \x01(\x0b\x32$.autonomic.ext.telemetry.EulerAnglesH\x00\x12\x42\n\x0frotation_matrix\x18\x03 \x01(\x0b\x32\'.autonomic.ext.telemetry.RotationMatrixH\x00\x42\r\n\x0borientation\"\xa7\x02\n\x14ThreeAxisSensorState\x12M\n\x0bsensor_type\x18\x02 \x01(\x0e\x32\x38.autonomic.ext.telemetry.ThreeAxisSensorState.SensorType\x12\t\n\x01x\x18\x03 \x01(\x01\x12\t\n\x01y\x18\x04 \x01(\x01\x12\t\n\x01z\x18\x05 \x01(\x01\"\x9e\x01\n\nSensorType\x12\x14\n\x10TYPE_UNSPECIFIED\x10\x00\x12\r\n\tGYRO_DATA\x10\x01\x12\x11\n\rROTATION_RATE\x10\x02\x12\x16\n\x12\x41\x43\x43\x45LEROMETER_DATA\x10\x03\x12\x15\n\x11\x41\x43\x43\x45LERATION_RATE\x10\x04\x12\x15\n\x11MAGNETOMETER_DATA\x10\x05\x12\x12\n\x0eMAGNETIC_FIELD\x10\x06\x42\x87\x01\n\x1b\x63om.autonomic.ext.telemetryB\rDynamicsProtoP\x01ZNgithub.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/telemetry\xf8\x01\x01\xa2\x02\x03\x41UTb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'autonomic.ext.telemetry.dynamics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.autonomic.ext.telemetryB\rDynamicsProtoP\001ZNgithub.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/telemetry\370\001\001\242\002\003AUT'
  _globals['_QUATERNION']._serialized_start=67
  _globals['_QUATERNION']._serialized_end=123
  _globals['_EULERANGLES']._serialized_start=125
  _globals['_EULERANGLES']._serialized_end=180
  _globals['_ROTATIONMATRIX']._serialized_start=183
  _globals['_ROTATIONMATRIX']._serialized_end=316
  _globals['_ORIENTATION']._serialized_start=319
  _globals['_ORIENTATION']._serialized_end=536
  _globals['_THREEAXISSENSORSTATE']._serialized_start=539
  _globals['_THREEAXISSENSORSTATE']._serialized_end=834
  _globals['_THREEAXISSENSORSTATE_SENSORTYPE']._serialized_start=676
  _globals['_THREEAXISSENSORSTATE_SENSORTYPE']._serialized_end=834
# @@protoc_insertion_point(module_scope)
