# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: autonomic/ext/common/oem_data.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'autonomic/ext/common/oem_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#autonomic/ext/common/oem_data.proto\x12\x1c\x61utonomic.ext.common.oemdata\x1a\x19google/protobuf/any.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb7\x06\n\x07OemData\x12\x17\n\x0f\x61\x64\x64itional_data\x18\x01 \x01(\t\x12\"\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any\x12\x44\n\x08\x64\x61ta_map\x18\x03 \x03(\x0b\x32\x32.autonomic.ext.common.oemdata.OemData.DataMapEntry\x1a^\n\x0c\x44\x61taMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12=\n\x05value\x18\x02 \x01(\x0b\x32..autonomic.ext.common.oemdata.OemData.OemValue:\x02\x38\x01\x1a\xbf\x03\n\x08OemValue\x12\x14\n\nbool_value\x18\x01 \x01(\x08H\x00\x12\x13\n\tint_value\x18\x02 \x01(\x03H\x00\x12\x16\n\x0c\x64ouble_value\x18\x03 \x01(\x01H\x00\x12\x16\n\x0cstring_value\x18\x04 \x01(\tH\x00\x12\x15\n\x0b\x62ytes_value\x18\x05 \x01(\x0cH\x00\x12Q\n\x0fint_array_value\x18\x06 \x01(\x0b\x32\x36.autonomic.ext.common.oemdata.OemData.OemIntArrayValueH\x00\x12W\n\x12string_array_value\x18\x07 \x01(\x0b\x32\x39.autonomic.ext.common.oemdata.OemData.OemStringArrayValueH\x00\x12U\n\x11\x62ytes_array_value\x18\x08 \x01(\x0b\x32\x38.autonomic.ext.common.oemdata.OemData.OemBytesArrayValueH\x00\x12\x35\n\x0ftimestamp_value\x18\t \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x00\x42\x07\n\x05value\x1a$\n\x13OemStringArrayValue\x12\r\n\x05value\x18\x01 \x03(\t\x1a!\n\x10OemIntArrayValue\x12\r\n\x05value\x18\x01 \x03(\x03\x1a>\n\x12OemBytesArrayValue\x12\r\n\x05value\x18\x01 \x03(\x0c\x12\x19\n\x11value_description\x18\x02 \x01(\tB\x88\x01\n com.autonomic.ext.common.oemdataB\x0cOemDataProtoP\x01ZKgithub.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/common\xf8\x01\x01\xa2\x02\x03\x41UTb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'autonomic.ext.common.oem_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n com.autonomic.ext.common.oemdataB\014OemDataProtoP\001ZKgithub.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/common\370\001\001\242\002\003AUT'
  _globals['_OEMDATA_DATAMAPENTRY']._loaded_options = None
  _globals['_OEMDATA_DATAMAPENTRY']._serialized_options = b'8\001'
  _globals['_OEMDATA']._serialized_start=130
  _globals['_OEMDATA']._serialized_end=953
  _globals['_OEMDATA_DATAMAPENTRY']._serialized_start=272
  _globals['_OEMDATA_DATAMAPENTRY']._serialized_end=366
  _globals['_OEMDATA_OEMVALUE']._serialized_start=369
  _globals['_OEMDATA_OEMVALUE']._serialized_end=816
  _globals['_OEMDATA_OEMSTRINGARRAYVALUE']._serialized_start=818
  _globals['_OEMDATA_OEMSTRINGARRAYVALUE']._serialized_end=854
  _globals['_OEMDATA_OEMINTARRAYVALUE']._serialized_start=856
  _globals['_OEMDATA_OEMINTARRAYVALUE']._serialized_end=889
  _globals['_OEMDATA_OEMBYTESARRAYVALUE']._serialized_start=891
  _globals['_OEMDATA_OEMBYTESARRAYVALUE']._serialized_end=953
# @@protoc_insertion_point(module_scope)
