# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from autonomic.ext.edge import edge_pb2 as autonomic_dot_ext_dot_edge_dot_edge__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in autonomic/ext/edge/edge_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EdgeStub(object):
    """#### Introduction

    The Edge API is the primary communication mechanism between devices,
    such as vehicle TCUs and PIDs, and the Autonomic service.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Keepalive = channel.unary_unary(
                '/autonomic.ext.edge.Edge/Keepalive',
                request_serializer=autonomic_dot_ext_dot_edge_dot_edge__pb2.KeepaliveRequest.SerializeToString,
                response_deserializer=autonomic_dot_ext_dot_edge_dot_edge__pb2.KeepaliveResponse.FromString,
                _registered_method=True)
        self.Publish = channel.stream_unary(
                '/autonomic.ext.edge.Edge/Publish',
                request_serializer=autonomic_dot_ext_dot_edge_dot_edge__pb2.PublishRequest.SerializeToString,
                response_deserializer=autonomic_dot_ext_dot_edge_dot_edge__pb2.PublishResponse.FromString,
                _registered_method=True)
        self.PublishWithAck = channel.stream_stream(
                '/autonomic.ext.edge.Edge/PublishWithAck',
                request_serializer=autonomic_dot_ext_dot_edge_dot_edge__pb2.PublishWithAckRequest.SerializeToString,
                response_deserializer=autonomic_dot_ext_dot_edge_dot_edge__pb2.PublishWithAckResponse.FromString,
                _registered_method=True)


class EdgeServicer(object):
    """#### Introduction

    The Edge API is the primary communication mechanism between devices,
    such as vehicle TCUs and PIDs, and the Autonomic service.

    """

    def Keepalive(self, request, context):
        """`Keepalive()` is used to maintain the connection from the client
        to the server. Clients send their current notion of time, and
        servers respond with their current notion of time, allowing clients
        to quickly get a good approximation of the current time before more
        sophisticated clock synchronization mechanisms are used.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Publish(self, request_iterator, context):
        """Publish a stream of telemetry / events to the server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishWithAck(self, request_iterator, context):
        """Publish a stream of telemetry / events to the server, receiving
        a stream of acknowledgments from the server in response.

        A response with no error_status guarantees that the data was
        successfully ingested into the platform.

        A response with an error status of TRANSIENT_FAILURE indicates
        that the data was not ingested due to a transient error and that the
        client should re-attempt at a later time.

        A response with an error status of PERMANENT_FAILURE indicates
        that the data was not ingested due to bad / invalid device credentials.
        The device should bootstrap and re-attempt.

        A response with an error status of TELEMETRY_REJECTED indicates
        that the data was not ingested due to malformed data.  The device
        should not re-attempt.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EdgeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Keepalive': grpc.unary_unary_rpc_method_handler(
                    servicer.Keepalive,
                    request_deserializer=autonomic_dot_ext_dot_edge_dot_edge__pb2.KeepaliveRequest.FromString,
                    response_serializer=autonomic_dot_ext_dot_edge_dot_edge__pb2.KeepaliveResponse.SerializeToString,
            ),
            'Publish': grpc.stream_unary_rpc_method_handler(
                    servicer.Publish,
                    request_deserializer=autonomic_dot_ext_dot_edge_dot_edge__pb2.PublishRequest.FromString,
                    response_serializer=autonomic_dot_ext_dot_edge_dot_edge__pb2.PublishResponse.SerializeToString,
            ),
            'PublishWithAck': grpc.stream_stream_rpc_method_handler(
                    servicer.PublishWithAck,
                    request_deserializer=autonomic_dot_ext_dot_edge_dot_edge__pb2.PublishWithAckRequest.FromString,
                    response_serializer=autonomic_dot_ext_dot_edge_dot_edge__pb2.PublishWithAckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'autonomic.ext.edge.Edge', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('autonomic.ext.edge.Edge', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Edge(object):
    """#### Introduction

    The Edge API is the primary communication mechanism between devices,
    such as vehicle TCUs and PIDs, and the Autonomic service.

    """

    @staticmethod
    def Keepalive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autonomic.ext.edge.Edge/Keepalive',
            autonomic_dot_ext_dot_edge_dot_edge__pb2.KeepaliveRequest.SerializeToString,
            autonomic_dot_ext_dot_edge_dot_edge__pb2.KeepaliveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Publish(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/autonomic.ext.edge.Edge/Publish',
            autonomic_dot_ext_dot_edge_dot_edge__pb2.PublishRequest.SerializeToString,
            autonomic_dot_ext_dot_edge_dot_edge__pb2.PublishResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishWithAck(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/autonomic.ext.edge.Edge/PublishWithAck',
            autonomic_dot_ext_dot_edge_dot_edge__pb2.PublishWithAckRequest.SerializeToString,
            autonomic_dot_ext_dot_edge_dot_edge__pb2.PublishWithAckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
