import React, { useRef, useState, useEffect } from "react";
import "amazon-connect-streams";
import { Container, Header, StatusIndicator, Box } from "@cloudscape-design/components";
import { useConnect } from "./ConnectContext";

export interface ConnectCCPProps {
  connectInstanceUrl: string;
  onContactConnecting?: (contact: connect.Contact) => void;
  onContactConnected?: (contact: connect.Contact) => void;
  onContactEnded?: (contact: connect.Contact) => void;
}

export const ConnectCCP: React.FC<ConnectCCPProps> = ({
  connectInstanceUrl,
  onContactConnecting,
  onContactConnected,
  onContactEnded,
}) => {
  const ccpRef = useRef<HTMLDivElement>(null);
  const [agentState, setAgentState] = useState<string>("Connecting...");
  const [initialized, setInitialized] = useState(false);
  /** True when another component already owns the CCP iframe (see below). */
  const [ccpOwnedElsewhere, setCcpOwnedElsewhere] = useState(false);
  const { panelEnabled, requestConnect, initialized: panelInitialized } = useConnect();

  // Opening Agent Workspace IS the agent's opt-in to go online. Delegate to the
  // app-wide panel, which owns the one CCP this page may have (issue
  // 2026-09-24-connect-login-popup-on-every-page-load).
  useEffect(() => {
    if (panelEnabled) requestConnect();
  }, [panelEnabled, requestConnect]);

  useEffect(() => {
    if (!ccpRef.current || initialized) return;

    // Subscriber registration is separate from initCCP on purpose: both
    // `connect.agent` and `connect.contact` are safe to call against an
    // already-initialised SDK — the docs state the callback fires immediately
    // for an existing agent, and `connect.contact` also fires for contacts
    // that existed when Streams was initialised.
    const wireSubscribers = () => {
      connect.agent((agent) => {
        setAgentState(agent.getState().name);
        agent.onStateChange((stateChange) => {
          setAgentState(stateChange.newState);
        });
      });

      connect.contact((contact) => {
        contact.onConnecting(() => onContactConnecting?.(contact));
        contact.onConnected(() => onContactConnected?.(contact));
        contact.onEnded(() => onContactEnded?.(contact));
      });
    };

    try {
      // `connect.core` is a GLOBAL singleton and Connect Streams supports
      // exactly ONE initCCP per page load. `CCPPanel` is mounted app-wide for
      // every isConnectAgent user (App.tsx), so by the time this component
      // renders the SDK is normally ALREADY initialised. Calling initCCP again
      // throws "Attempted to call initCCP when an iframe generated by initCCP
      // already exists" — CCPPanel carries this same guard and this component
      // was missed. See issues/2026-06-22-cms-ccp-double-init-and-framing/.
      //
      // We cannot adopt the existing iframe: it belongs to whichever component
      // called initCCP first. So wire up the subscribers (which is what drives
      // this workspace's contact-to-vehicle resolution) and tell the agent
      // where the live CCP actually is, rather than leaving a dead container
      // spinning "Connecting..." forever.
      if ((connect as any).core && (connect as any).core.initialized) {
        wireSubscribers();
        setCcpOwnedElsewhere(true);
        setInitialized(true);
        return;
      }

      // The app-wide panel will start the CCP, because we requested it above.
      // Never start a second one here: it would own the iframe, and it would die
      // when this route unmounts. This effect re-runs when the panel reports it
      // is initialised, and the branch above then wires the subscribers.
      if (panelEnabled) return;

      // Fallback, for when no app-wide panel exists for this user.
      connect.core.initCCP(ccpRef.current, {
        ccpUrl: connectInstanceUrl,
        loginPopup: true,
        loginPopupAutoClose: true,
        loginUrl: connectInstanceUrl.replace('/ccp-v2', ''),
        softphone: { allowFramedSoftphone: true },
        pageOptions: { enableAudioDeviceSettings: true, enablePhoneTypeSettings: true },
      });

      wireSubscribers();
      setInitialized(true);
    } catch (e) {
      console.error("Failed to initialize CCP:", e);
      setAgentState("Error - refresh page");
    }
  }, [panelEnabled, panelInitialized]);

  return (
    <Container header={<Header variant="h2">Contact Control Panel</Header>}>
      <style>{`
        #ccp-container iframe {
          width: 100% !important;
          height: 100% !important;
          border: none !important;
        }
      `}</style>
      <div
        id="ccp-container"
        ref={ccpRef}
        style={{ width: "100%", height: ccpOwnedElsewhere ? 0 : "460px", overflow: "hidden" }}
      />
      {ccpOwnedElsewhere && (
        <Box color="text-body-secondary" fontSize="body-s">
          The contact panel is open in the floating agent widget (bottom-right).
          Connect allows one control panel per page, so this workspace tracks the
          active contact and shows its vehicle context rather than opening a
          second panel.
        </Box>
      )}
      <Box margin={{ top: "s" }}>
        <StatusIndicator type={agentState === "Available" ? "success" : agentState.includes("Error") ? "error" : "loading"}>
          {agentState}
        </StatusIndicator>
      </Box>
    </Container>
  );
};
