# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: autonomic/ext/telemetry/enumerations/battery_load_status.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'autonomic/ext/telemetry/enumerations/battery_load_status.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n>autonomic/ext/telemetry/enumerations/battery_load_status.proto\x12\x36\x61utonomic.ext.telemetry.enumerations.batteryLoadStatus*\xa2\x01\n\x11\x42\x61tteryLoadStatus\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x12\n\x0e\x41\x43\x43\x45SSORY_MODE\x10\x01\x12\x14\n\x10NORMAL_OPERATION\x10\x02\x12\x0f\n\x0bLOW_BATTERY\x10\x03\x12\x11\n\rBATTERY_FAULT\x10\x04\x12\x0f\n\x0b\x45RROR_STATE\x10\x05\x12!\n\x1dOVERLOAD_SHEDDING_IN_PROGRESS\x10\x06\x42\xaa\x01\n(com.autonomic.ext.telemetry.enumerationsB\x16\x42\x61tteryLoadStatusProtoP\x01Z[github.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/telemetry/enumerations\xf8\x01\x01\xa2\x02\x03\x41UTb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'autonomic.ext.telemetry.enumerations.battery_load_status_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n(com.autonomic.ext.telemetry.enumerationsB\026BatteryLoadStatusProtoP\001Z[github.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/telemetry/enumerations\370\001\001\242\002\003AUT'
  _globals['_BATTERYLOADSTATUS']._serialized_start=123
  _globals['_BATTERYLOADSTATUS']._serialized_end=285
# @@protoc_insertion_point(module_scope)
