# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: autonomic/ext/telemetry/enumerations/vehicle_audio_source.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'autonomic/ext/telemetry/enumerations/vehicle_audio_source.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n?autonomic/ext/telemetry/enumerations/vehicle_audio_source.proto\x12\x37\x61utonomic.ext.telemetry.enumerations.vehicleAudioSource*\xa3\x02\n\x12VehicleAudioSource\x12\r\n\tUNDEFINED\x10\x00\x12\x0f\n\x0b\x41M_FM_RADIO\x10\x01\x12\x11\n\rCD_DVD_SYSTEM\x10\x02\x12\x13\n\x0fSATELLITE_RADIO\x10\x03\x12\x13\n\x0fVOICE_ASSISTANT\x10\x04\x12\x1c\n\x18ON_BOARD_TELEMATICS_UNIT\x10\x05\x12\x13\n\x0f\x42LUETOOTH_PHONE\x10\x06\x12\r\n\tAUX_INPUT\x10\x07\x12\x15\n\x11NAVIGATION_SYSTEM\x10\x08\x12\x13\n\x0f\x42LUETOOTH_AUDIO\x10\t\x12\x07\n\x03USB\x10\n\x12\x08\n\x04IPOD\x10\x0b\x12\x16\n\x12OTHER_OEM_SPECIFIC\x10\x0c\x12\x17\n\x13NO_SOURCE_SPECIFIED\x10\rB\xab\x01\n(com.autonomic.ext.telemetry.enumerationsB\x17VehicleAudioSourceProtoP\x01Z[github.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/telemetry/enumerations\xf8\x01\x01\xa2\x02\x03\x41UTb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'autonomic.ext.telemetry.enumerations.vehicle_audio_source_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n(com.autonomic.ext.telemetry.enumerationsB\027VehicleAudioSourceProtoP\001Z[github.com/autonomic-ai/external-protos/src/main/proto/autonomic/ext/telemetry/enumerations\370\001\001\242\002\003AUT'
  _globals['_VEHICLEAUDIOSOURCE']._serialized_start=125
  _globals['_VEHICLEAUDIOSOURCE']._serialized_end=416
# @@protoc_insertion_point(module_scope)
